### ISSUE TITLE
请问：如何设置Shift_R+space切换简/繁？

### ISSUE THREAD

**Issue by Kotsuha** [rime/weasel#1016]
**上报前请检查**
- [X] 我遇到的问题没有其他人在 issue 里提到过
- [X] 我的小狼毫版本于 rime/weasel 下载
- [X] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 (OS Build 19045.3570)
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**

不知能否在这问客制化问题，如果这类问题应该发在别的地方请告诉我。

我使用朙月拼音，我想设置：
Left Shift + Space 切换全形/半形
Right Shift + Space 切换简体/繁体

试了这样写，不行。

```
# default.custom.yaml
patch:
  key_binder:
    bindings:
    - { accept: "Shift_L+space", toggle: full_shape, when: always}
    - { accept: "Shift_R+space", toggle: simplification, when: always}
```

在 Issue 搜寻到[这个](https://github.com/rime/weasel/issues/239)，试了 "Shift+Shift_R+space" 也不行。

请问如何设置呢？

**Comment by Techince** [comment]
@Kotsuha 试试这个版本。要求方案里配置「s2t」开关：
![image](https://github.com/rime/weasel/assets/12376669/b0dd353e-7adc-4466-8b65-48c2e34f790a)

若此开关在方案的第四个位置，默认快捷键是「Ctrl+Shift+4」，可以将此快捷键映射成「Shift+Shift_R+Space」

**Comment by Kotsuha** [comment]
装了 [weasel-0.15.1.0-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe) 以后，把 luna_pinyin.custom.yaml 改成如下

```
# luna_pinyin.custom.yaml

patch:
  switches:
    - name: ascii_mode        # 转换开关
      reset: 0          # reset 0的作用是当从其他方案切换到本方案时，
      states: [ "中文", "西文" ]      # 重设为指定的状态，而不保留在前一个方案中设定的状态。
    - name: full_shape        # 选择输入方案后通常需要立即输入中文，故重设ascii_mode = 0；
      states: [ "🌙️", "🌕️" ]      # 而全/半角则可沿用之前方案中的用法。
    - name: s2t
      states: [ 简体, 繁体 ]
      reset: 0
  key_binder:
    bindings:
      - { accept: "Shift+Shift_R+space", toggle: s2t, when: always }

```

按「左 Shift + Space」没反应（会输入一个空格）

但如果把 bindings 改成

```
  key_binder:
    bindings:
      - { accept: "Shift+space", toggle: s2t, when: always }
```

按「左 Shift + Space」会看到繁体/简体切换

不知道是我哪里做错了... 或者电脑问题...
