### ISSUE TITLE
形码用户不知道某些词是否在词库中是否有解决方法?

### ISSUE THREAD

**Issue by vvyoko** [rime/weasel#1028]
在home那边也发了一次
但是因为可能想要获取weasel的输入
所以在此也发一遍

最近在整理五笔词库,发现一个问题
有些词我是无论如何都不会输入的...
比方说 大团圆,都是先打大,再打团圆
主要原因就是不确定词库里有没有...
感觉这是一直以来的痛点了.
拼音根本不用管,直接输就行了
五笔好像没啥好解决的办法...

有没有可能有这样的脚本,记录上一次选取的词和这次选取的词
然后查询是否在词库中,然后通知下,下次就直接打了
但脚本好像没通知功能?

在windows上有办法获用编程方式获取rime的输入吗
如果可以自己实现也行...

**Comment by fxliang** [comment]
你想要的功能应该是形码方案下的
```yaml
patch:
  translator/enable_user_dict: true
  translator/encode_commit_history: true
```
在方案.custom.yaml下加上patch部署之后，主可以打大，团圆，然后大团圆
