### ISSUE TITLE
解析weasel.custom.yaml生成的weasel.yaml文件不完整

### ISSUE THREAD

**Issue by chenzhiwei** [rime/weasel#1033]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.2715
 - 小狼毫版本: 0.15.0

**描述遇到的问题**
weasel.custom.yaml内容：
```
patch:
  style:
    horizontal: true
    inline_preedit: false
```
生成的 build/weasel.yaml里的style部分如下：
```
style:
  horizontal: true
  inline_preedit: false
```
**这会导致看不到候选框或候选框格式出问题**

weasel.custom.yaml使用如下写法就没任何问题了：
```
patch:
  style/horizontal: true
  style/inline_preedit: false

#生成的weasel.yaml style部分如下：
style:
  color_scheme: aqua
  comment_font_face: "Microsoft YaHei"
  comment_font_point: 14
  display_tray_icon: false
  font_face: "Microsoft YaHei"
  font_point: 14
  fullscreen: false
  horizontal: true
  inline_preedit: false
  label_font_face: "Microsoft YaHei"
  label_font_point: 14
  label_format: "%s."
  layout:
    align_type: center
    border_width: 3
    candidate_spacing: 5
    corner_radius: 4
    hilite_padding: 2
    hilite_spacing: 4
    margin_x: 12
    margin_y: 12
    max_height: 0
    max_width: 0
    min_height: 0
    min_width: 160
    round_corner: 4
    shadow_offset_x: 4
    shadow_offset_y: 4
    shadow_radius: 0
    spacing: 10
  mark_text: ""
  preedit_type: composition
  vertical_auto_reverse: false
  vertical_text: false
  vertical_text_left_to_right: false
  vertical_text_with_wrap: false
```

**复现步骤**
重现问题的步骤，如：
1. 打开 '...' 软件
2. 输入 '...'
3. 进行 '...' 操作
4. 遇到了 '...' 问题

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里
