### ISSUE TITLE
CI 版本中，inline_preedit 为 true 时，行内预编辑区域在切换窗口后消失

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1041]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 19044.3570
 - 小狼毫版本: Commit CI 167

**描述遇到的问题**
#985 引入分应用设置 inline_preedit 情况，导致 Chrome 下预编辑区消失。

全新系统，所有设置未更改，weasel.custom.yaml 设定如下：
```yaml
inline_preedit: true

app_options:
  flow.launcher.exe:
    inline_preedit: false
```

1. 打开 Brave/Chrome 浏览器，正常显示 inline_preedit
2. 打开 Flow Launcher，正常在 weasel 窗口内显示 preedit 区域
3. 再次切换为 Brave/Chrome 浏览器，发生 bug，不显示 preedit 消失（在 Keypirinha 中，还会出现同时显示 inline_preedit 和 窗口内 preedit 的情况）

![image](https://github.com/rime/weasel/assets/76689045/0bad0e67-d36a-4e50-9796-d85dacd1edf7)

**视频**

[20230816191554.webm](https://github.com/rime/weasel/assets/76689045/3d79728e-1e91-4820-84de-82f5223ba3e0)
