### ISSUE TITLE
border 为 0 和 1 导致 notification tip 残缺；border 大于等于 3 时额外边框渲染 bug

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1082]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我在使用小狼毫的最新发布版本后的 CI 构建
- [x] 我的小狼毫版本于 rime/weasel 下载

**操作系统信息**
 - OS 详细版本: [ Windows 10 19044.3803]
 - 小狼毫版本: [ https://github.com/rime/weasel/commit/fb80f61c0bd6702b24675493fa7ca3935e3d3078 ]

## border = 0 或 1 时，状态通知残缺不全，或者直接不显示

```yaml
# weasel.yaml
show_notifications: true
style:
  layout:
    border_width: 0
```

效果

![image](https://github.com/rime/weasel/assets/76689045/e9d52797-80f3-440f-99f1-80c3d9ddbd19)

只要设定 border = 3 以上就正常显示

## border >= 3 时，且设置 border_color = back_color，candidate_back_color = candidate_border_color 多显示几像素背景边框

在配色中设定 border 颜色和背景颜色相同：

```yaml
style:
  layout:
    border_width: 3
preset_color_schemes:
  xx:
    back_color: 0xECEFF4
    border_color: 0xECEFF4
    hilited_candidate_back_color: 0x8FBCBB
    hilited_candidate_border_color: 0x8FBCBB
```

期待效果：边框颜色完全和背景颜色相同，类似于 border = 0 的效果，实际效果

![image](https://github.com/rime/weasel/assets/76689045/55cf0a52-2921-48ce-8a05-820f4ef711f0)

设置为 2，1 无此问题

![image](https://github.com/rime/weasel/assets/76689045/fb708c6c-a780-473e-9180-059c7a463f5c)
