### ISSUE TITLE
默认是中文输出，设置weasel.custom.yaml的cmd为ascii_mode: true,cmd无法自动切换英文

### ISSUE THREAD

**Issue by Ausli** [rime/weasel#1095]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3085)
 - 小狼毫版本:  0.15.0.0 f69f2c2

**描述遇到的问题**
设置weasel.custom.yaml的cmd为ascii_mode: true,cmd无法切换英文

**复现步骤**
设置weasel.custom.yaml的cmd为ascii_mode: true,打开cmd

**预期行为**
打开cmd.exe将中文切换为英文

**用户文件**
这是weasel.custom.yaml文件内容
```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.0.0
  generator: "Weasel::UIStyleSettings"
  modified_time: "Fri Dec  8 16:03:17 2023"
  rime_version: 1.9.0

patch:
  "preset_color_schemes/wechat":
    name: 微信／wechat
    author: 空山明月 <sqqlove123@163.com>
    back_color: 0xFFFFFF
    border_color: 0x9F9F9F
    text_color: 0x202121
    hilited_label_color: 0xDBDBDB
    hilited_text_color: 0x202121
    hilited_back_color: 0xE4EBF0
    hilited_candidate_text_color: 0xF8FBF4
    hilited_candidate_back_color: 0x78AF22 # 微信绿 0x78AF22，魅蓝紫 0xC73262，活力橙 0x2283D9
    hilited_comment_text_color: 0xDBDBDB
    candidate_text_color: 0x555555
    comment_text_color: 0x9F9F9F


  "style/color_scheme": wechat
  "style/horizontal": true
  app_options:
  cmd.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true

```
**用户文件夹**
[User.zip](https://github.com/rime/weasel/files/14081487/User.zip)

**其他补充说明**
如果有其他补充说明，可以写在这里
