### ISSUE TITLE
注音輸入中該如何設定默認英文

### ISSUE THREAD

**Issue by B-2U** [rime/weasel#1101]
**上报前请检查**
- [ v ] 我遇到的问题没有其他人在 issue 里提到过
- [ v ] 我的小狼毫版本于 rime/weasel 下载
- [ v ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 10 22H2 19045.3930]
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
無法設定成默認英文

這個問題可能已經是老生常談，在大量的嘗試後依然不知該如何處理，故來此請教，還請見諒

已查閱了大部分相關的issue，以及wiki中的 [一例、默認英文輸出 ](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E9%BB%98%E8%AA%8D%E8%8B%B1%E6%96%87%E8%BC%B8%E5%87%BA)
嘗試過建立`bopomofo.schema.custom.yaml` , 修改 `default.custom.yaml`, 並寫入 
```yaml
patch:
  "switches/@0/reset": 1
```
或
```yaml
switches:
  - name: ascii_mode
    reset: 1
    states: ["中文", "西文"]
```
或直接修改`bopomofo.schema.yaml` 將reset改爲1

先提前感謝幫助！
