### ISSUE TITLE
小鹤双拼 切换窗口后 重置输入法 状态

### ISSUE THREAD

**Issue by Evifly** [rime/weasel#1117]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 22621.3155
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
使用小鹤双拼时，切换任意窗口都会导致输入法切换回繁体模式

**复现步骤**
重现问题的步骤，如：
1. 打开 '任意' 软件
2. 输入 '任意'字符，当前为繁体，通过快捷键改回简体，
3. 切换任意软件，再切换回上一窗口或其它窗口，输入法变成繁体

临时解决办法：
在“double_pinyin_flypy.schema.yaml”中的“switches”项添加reset:1
"""
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    reset: 1 
    states: [ 漢字, 汉字 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
"""

**预期行为**
期望在下一版本中可以调整。

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by mirtlecn** [comment]
这是预期行为。你提到的「临时解决办法」是正确的处理办法。

此外，注释掉 reset 一行，在 default.yaml 中的 `switcher/save_options:` 下写 option 名，可以让程序记住你的选项开关状态。

```yaml
# xxx.schema.yaml
switches:
  - name: option_name
    # reset: 0
    states: [A, B]
```

```yaml
# default.yaml
switcher:
  save_options:
    - option_name
```
