### ISSUE TITLE
Windows 11 下，vim_mode 在终端和 launcher 串台

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1153]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 23H2 10.0.22631 ]
 - 小狼毫版本: [ https://github.com/rime/weasel/actions/runs/8323931518 ]

**描述遇到的问题**

vim_mode 串台，本该再 console 和 wt.exe 生效，但却在 flow launcher 中生效

复现条件不明，但在设置下面的条目后，使用一段时间后必定会出现串台问题。尝试过几次复现，但搞不清楚到底是怎么触发的。

```yaml
# weasel.custom.yaml
patch:
  app_options/flow.launcher.exe/ascii_mode: false
  app_options/windowsterminal.exe/vim_mode: true
  app_options/conhost.exe/vim_mode: true
```

**预期行为**
仅仅在终端里面生效
