### ISSUE TITLE
候选项中出现emoji时导致输入法行高增加

### ISSUE THREAD

**Issue by Yikai-Liao** [rime/weasel#1175]
**上报前请检查**
- [ ✔] 我遇到的问题没有其他人在 issue 里提到过
- [ ✔] 我的小狼毫版本于 rime/weasel 下载
- [ ✔] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.4239
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
候选项中出现emoji时导致输入法行高增加。具体情况与鼠须管中已经解决的[issue](https://github.com/rime/squirrel/issues/504)一致（鼠须管已经在2021年修复该bug:：https://github.com/rime/squirrel/pull/559 ）。希望可以跟进修复这个bug。

![image](https://github.com/rime/weasel/assets/110762732/b9394ef3-8d0f-48c8-9fab-5fb700477600)

**Comment by fxliang** [comment]
检查确认#1177的产出，适当调整 新增的两个参数的数值，看是否可以解决这个问题吧。

**Comment by Yikai-Liao** [comment]
我应该怎么测试呢？nightly build还没有编译这个新版本

**Comment by fxliang** [comment]
https://github.com/rime/weasel/actions/runs/8598045790
下方的artifact下载，里面有安装包

基本原理大概是通过linespacing调大行距，通过baseline调整基线位置，相当于调大了出来的back的高度（竖排文字时宽度）。

但是呢，如果使用的两种字体的基线位置相差太多的话，还是会无法对齐行内的不同字体的字形的，这个是字体设计的问题。

```yaml
patch:
  style/layout/baseline: 100  # 100% of font point height
  style/layout/linespacing: 140   # 140% of font point height, when flicker happened, should be a value larger than 100
```
