### ISSUE TITLE
使用句号翻页会把句号也追加到 preedit 里面

### ISSUE THREAD

**Issue by dec32** [rime/weasel#1197]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.4291
 - 小狼毫版本: 0.15.0.0-0507bf7

**描述遇到的问题**

使用句号翻页，翻到第二页时，输入更多编码，新输入的编码前会出现一个句号。

**复现步骤**

1. 输入任意编码，比如 `wo`；
2. 单击 <kbd>.</kbd>，翻到第二页；
3. 再追加任意编码，比如 `s`；
4. 观察到 preedit 中的内容变成了 `wo.s`

（更一般的，只要翻到偶数页，就会发生上述的现象，翻到奇数页则不会）

**预期行为**

<kbd>.</kbd> 只应用于翻页，不应用于编码

**截图**

敲击 <kbd>w</kbd> <kbd>o</kbd> 的效果：
![](https://github.com/rime/weasel/assets/56337978/e330f9d3-dd97-4d48-a833-780303c5352f)

敲击 <kbd>w</kbd> <kbd>o</kbd> <kbd>.</kbd> 的效果：
![](https://github.com/rime/weasel/assets/56337978/4d6cd1c4-acc5-487f-8af2-c8749a30eb90)

敲击 <kbd>w</kbd> <kbd>o</kbd> <kbd>.</kbd> <kbd>s</kbd> 的效果：
![](https://github.com/rime/weasel/assets/56337978/c7e485b1-23d5-493e-bd69-4cf7d045bcb3)

敲击 <kbd>w</kbd> <kbd>o</kbd> <kbd>.</kbd> <kbd>s</kbd> <kbd>←Backspace</kbd> 的效果：
![](https://github.com/rime/weasel/assets/56337978/d0b2c9af-6855-41a4-a746-1d77876e3411)

**用户文件**

default.custom.yaml:

```YAML
customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.0.0
  generator: "Rime::SwitcherSettings"
  modified_time: "Wed Apr 17 17:03:16 2024"
  rime_version: 1.11.0
patch:
  key_binder/bindings/+:
    - {accept: Control+Shift+Space, select: .next, when: always}
    - {accept: Control+Shift+J, select: japanese, when: always}
    - {accept: Control+Shift+H, select: double_pinyin_flypy, when: always}
    - {accept: Control+Shift+M, select: moran_sentence, when: always}
    - {accept: semicolon, send: 2, when: has_menu}
    - {accept: apostrophe, send: 3, when: has_menu}
  menu/page_size: 3
  schema_list:
    - {schema: japanese}
    - {schema: double_pinyin_flypy}
    - {schema: moran_sentence}
```

symbols.custom.yaml:

```YAML
patch:
  punctuator/half_shape:
    __include: punctuation:/half_shape
  punctuator/full_shape:
    __include: punctuation:/full_shape
```

punctuation.custom.yaml:

```YAML
patch:
  half_shape:
    # 常规的中文标点（￥ 除外，因为要拿 $ 来打 LaTeX 公式）
    '!' : ！
    '?' : ？ 
    '.' : 。 
    '^' : ……
    ';' : ；
    ':' : ：
    ',' : ，
    '\' : 、
    '_' : ——
    # 括号
    '(' : （
    ')' : ）
    '[' : 【
    ']' : 】
    '<' : 《 
    '>' : 》
    # 方引号
    '''' : { pair: [ 『, 』 ] }
    '"' : { pair: [ 「, 」] }
```
