### ISSUE TITLE
使用 Shift 键输入大小写字母时的候选项上屏问题

### ISSUE THREAD

**Issue by peng-dongzi** [rime/weasel#1332]
**上报前请检查**

- [x] 我遇到的问题没有其他人在 issue 里提到过

- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**

 - OS 详细版本: Windows 10 22H2 19045.4529

 - 小狼毫版本: 0.16.1.0

**问题、预期行为与复现步骤**

我之前是「微软拼音」输入法的用户，在使用「微软拼音」输入「我的 MacBook 很好用」这句话时，只需如下步骤：

1. 输入「我的」与一个空格

2. 按下 Shift + M，然后继续输入剩余字母「ac」

3. **按下 Shift + B，然后继续输入剩余字母「ook」与一个空格**

4. 最后输入「很好用」

![微软拼音输入](https://github.com/rime/weasel/assets/166092818/03f4bc7d-56af-4d3d-a989-649ca0a9ee38)

在这个过程中，由于只需要输入一个简短的大小写单词「MacBook」，我并不需要按 `Shift` 切换中英文状态就能输入完。将按下 `Shift` 切换中英文状态的时机留到需要输入大段英文的时候

然而，使用小狼毫输入法时，在上述第三个步骤中，会直接上屏「候选项 1」的中文：

![小狼毫输入](https://github.com/rime/weasel/assets/166092818/83db5bcd-faa4-4c1d-8a77-25a31fdd983a)

我该怎么做才能让小狼毫实现与微软拼音相同的输入体验？

**用户文件**

```yaml
  switch_key:
    Shift_L: commit_code   # 左 Shift 切换直接上屏字母
    Shift_R: commit_code   # 右 Shift 切换直接上屏字母
    Control_L: noop
    Control_R: noop
    Caps_Lock: noop
    Eisu_toggle: clear
```

**预期行为**

希望在输入简短的大小写单词时，无需切换中英文状态，能够直接输入字母而不会上屏「候选项 1」中的中文

**其他信息**

- 最近未做过任何硬件或软件变更。

- 我的猜测是 `Shift` 键的配置可能需要进一步调整，但无法确定具体需要怎么改。
