### ISSUE TITLE
切换方案时的提示不一致

### ISSUE THREAD

**Issue by byzod** [rime/weasel#1354]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
    OS 详细版本: Windows 10 21H2 19044.3086
    小狼毫版本: [0.16.1](https://github.com/rime/weasel/compare/0.16.0...0.16.1) (2024-06-06)

**描述遇到的问题**
首先感谢新增的`show_notifications`，终于可以把常用的几个切换都加上提示了，非常开心♥️
不然每次都是盲切，不能完全确认切到没有

然后遇到一个不是很大但是很奇怪的问题，由于是用两个方案来模拟英文输入模式，而这个通知看起来只是为单个方案里的option切换用的
切换方案时确实会有提示但是在不同的软件里提示不一样，而且提示所用文本比较奇怪

如图，在notepad里提示的是方案名，到firefox里就变成easyen的ascii图标和小鹤的emoji图标了（？
![An1](https://github.com/user-attachments/assets/99eba59d-0961-4592-9edf-c866e18906c9)

**复现步骤**
不知道要咋复现……

**预期行为**
给每个方案定义一个logo，用于切换到它时显示……？

**用户文件**
easy_en.custom.yaml，理论上用别的方案也行
```
patch:

  easy_en/+:
    split_sentence: false
    enable_sentence: false

  switches:
    - name: ascii_mode
      reset: 0
      states: [ Eng, Ａ ]

  engine/+:
    filters:
      # - lua_filter@en_spacer                          # 英语自动加空格
      - uniquifier
      # - lua_filter@easy_en_enhance_filter
```

double_pinyin_flypy.custom.yaml相关内容节选
```
patch:

  # 输入引擎
  engine/+:
    translators:
      - punct_translator
      - script_translator
      - lua_translator@date_translator                # 时间、日期、星期
      - lua_translator@lunar                          # 农历
      # - table_translator@custom_phrase                # 自定义短语 custom_phrase_double.txt
      - table_translator@melt_eng                     # 英文输入
      - table_translator@cn_en                        # 中英混合词汇
      - table_translator@radical_lookup               # 部件拆字反查
      - lua_translator@unicode                        # Unicode
      - lua_translator@number_translator              # 数字、金额大写
      - lua_translator@*calculator_translator          # 计算器
      - lua_translator@force_gc                       # 暴力 GC
    filters:
      - lua_filter@corrector                          # 错音错字提示
      - reverse_lookup_filter@radical_reverse_lookup  # 部件拆字滤镜
      - lua_filter@autocap_filter                     # 英文自动大写
      # - lua_filter@pin_cand_filter                    # 置顶候选项（顺序要求：置顶候选项 > Emoji > 简繁切换）
      - simplifier@emoji                              # Emoji
      - simplifier@traditionalize                     # 简繁切换
      - lua_filter@search@radical_pinyin              # 部件拆字辅码
      - lua_filter@reduce_english_filter              # 降低部分英语单词在候选项的位置
      # - lua_filter@en_spacer                          # 英语自动加空格
      - lua_filter@*cn_en_filter                      # 英语参与造词
      - uniquifier                                    # 去重
  
  # 将上屏的中英混合词汇写入词典，指定英语方案，需要开启用户词典
  en_schema: melt_eng
  # 次翻译器，英文
  melt_eng/+:
    enable_user_dict: true  # 开启用户词典
    
  # Lua 配置：为 corrector 格式化 comment，占位符为 {comment}
  # 默认 "{comment}" 输入 hun dun 时会在「馄饨」旁边生成 hún tun 的 comment
  # 例如左右加个括号 "({comment})" 就会变成 (hún tun)
  corrector: "({comment})"
  
  # Emoji
  emoji/+:
    opencc_config: emoji.custom.json
```
