### ISSUE TITLE
請問詞典擴展包是否會在重新部署時自動編譯，還是說需要手動編譯？

### ISSUE THREAD

**Issue by chinanoahli** [rime/weasel#1355]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 19041.1
 - 小狼毫版本: 0.16.1.38.28ace8e

我參考了 wiki 的 [辭典擴展包](https://github.com/rime/home/wiki/DictionaryPack) 頁面嘗試製備辭典，但是發現配置完成後，重新部署也不能生效，搜索部署log，也沒有任何關於我製作的辭典包的信息

似乎與 [#696@rime/home](https://github.com/rime/home/issues/696#issuecomment-1334828752) 有關，曾經可以自動編譯辭典擴展包，但現在似乎不可以了？

我已嘗試過把辭典擴展包放置於 `%AppData%/Rime`、`%AppData%/Rime/build` `%AppData%/Rime/build/bin` 這三個目錄中，均無法通過自動部署觸發構建

luna_pinyin_packs.schema.yaml:
```yaml
# Rime schema
# encoding: utf-8

schema:
  schema_id: luna_pinyin_packs    # 這個參數在wiki頁面中沒有具體說明，不確定是需要用戶新指定還是需要參照rime自帶的schema，所以照抄wiki了

translator:
  dictionary: luna_pinyin_packs    # 這個參數在wiki頁面中沒有具體說明，不確定是需要用戶新指定還是需要參照rime自帶的packs，所以照抄wiki了
  packs:
    - test_pack
```

test_pack.dict.yaml:
```yaml
---
name: test_pack
version: "2024.08.23"
sort: by_weight
use_preset_vocabulary: false
...

# 技能
大絕	da jue
# 省略剩餘內容
```

**Comment by chinanoahli** [comment]
經過對比有提到的issue以及一些別人分享的配置庫，得出解決辦法

首先應在 `XXXXschema.custom.yaml` (如rime配置根目錄下的 `luna_pinyin.custom.yaml` )追加：

```yaml
patch:

# 自定義詞庫
  translator:
    dictionary: dictName
```

然後定義詞典擴展包文件 `dictName.dict.yaml`：
```yaml
---
name: dictName
version: "2024.08.23"
sort: by_weight    # 按權重排列詞彙（必須，否則會造成候選詞排序錯亂）
use_preset_vocabulary: true    # 沒有找到相關說明（必須）
import_tables:      # 這裏應當通過 import_tables 來引用 rime 的自帶詞庫（或第三方詞庫），若你不想整個詞庫從頭設計的話
  - luna_pinyin
...

# 下列是自造詞列表
詞彙1	chihui
詞彙2	chihui
```
