### ISSUE TITLE
在Flow Launcher的搜索窗口中无法输入中文

### ISSUE THREAD

**Issue by serimood** [rime/weasel#1359]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 10 22H2（0S Build 19045.4780)]
 - 小狼毫版本: [ 0.16.1]
- Flow Launcher版本: [1.19.0]

**描述遇到的问题**
在通过alt+space快捷键打开flow launcher的搜索窗口后无法输入中文， weasel的状态栏为叉号

**用户文件**
```
# weasel.custom.yaml
patch:
  "style/color_scheme": dark_temple
  "style/inline_preedit": true
  app_options:
    code.exe:
      ascii_mode: true
```

**截图**
![weasel-issue-commit](https://github.com/user-attachments/assets/7ee28a03-7e62-44d6-a497-8cc055d05101)
![image](https://github.com/user-attachments/assets/9ff19ef7-b415-41c4-b6c1-044107114aff)

**其他补充说明**
尝试过alt+space以外的其他快捷键打开flow launcher
