### ISSUE TITLE
宫保拼音方案不显示候选框

### ISSUE THREAD

**Issue by wwssxx** [rime/weasel#1386]
**上报前请检查**
- [*] 我遇到的问题没有其他人在 issue 里提到过
- [*] 我的小狼毫版本于 rime/weasel 下载
- [*] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 家庭中文版 Insider Preview Dev  27718.1000]
 - 小狼毫版本: [ 0.16.3 ]

**描述遇到的问题**
将下载的
combo_pinyin.schema.yaml
combo_pinyin_briefs.yaml
combo_pinyin_layouts.yaml
combo_pinyin_split.schema.yaml
复制到了<用户文件夹>，使用默认的“七指禅”布局，发现无法正常输入，具体表现为：
并击后不显示候选框，汉字直接上屏，且前后不一致，如：重复并击 WEI 会显示“持吃持吃持吃……”，
只有在并击 FI 时才会显示候选框，但只有一个候选项。
折腾了很久，没成功。

![屏幕截图 2024-10-09 111038](https://github.com/user-attachments/assets/79d4c75c-3396-47c5-ae10-f727ec9755b5)

![屏幕截图 2024-10-09 111409](https://github.com/user-attachments/assets/205ff0f3-847f-41fa-8b38-fbac2ca62105)
![图片2](https://github.com/user-attachments/assets/ac4ed48f-f45d-48b9-937d-bfb1f198c04a)

**Comment by fxliang** [comment]
宫保拼音输入法测试未发现问题，当然我在试用的是最新的宫保拼音

**Comment by wwssxx** [comment]
> 宫保拼音输入法测试未发现问题，当然我在试用的是最新的宫保拼音

感谢大佬关注，一点一点排查找到原因了：
我在 default.custom 里面设置了
 - {accept: apostrophe, send: 2, when: has_menu}
 这一条按键定义导致的，所以，这算不算一个bug

**Comment by fxliang** [comment]
> > 宫保拼音输入法测试未发现问题，当然我在试用的是最新的宫保拼音
> 
> 感谢大佬关注，一点一点排查找到原因了： 我在 default.custom 里面设置了
> 
> * {accept: apostrophe, send: 2, when: has_menu}
>   这一条按键定义导致的，所以，这算不算一个bug

```yaml
speller:
  alphabet: "zyxwvutsrqponmlkjihgfedcba'"
  initials: "zyxwvutsrqponmlkjihgfedcba"
  delimiter: " "
  algebra:
    # 合併若干音節
    - derive/^o$/wo/
    - derive/^lo$/luo/
    - derive/^yo$/you/
    # 合併 ⟨o / ou⟩、⟨e / ei⟩兩組韻母
    #- derive/^([bpmf])?ou$/$1o/
    #- derive/^([zcsr]h?)?ei$/$1e/
    # 拼音音節一律後加隔音符號，避免音節切分歧義
    - "xform/^([a-z]+)$/$1'/"

```
大概是因为宫保拼音的方案里的alphabet里包含了apostrophe（就是`'`)吧
