### ISSUE TITLE
有概率第一个按键（a-z）不进入候选框直接上屏

### ISSUE THREAD

**Issue by hlc1209** [rime/weasel#1388]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.4112
 - 小狼毫版本: 0.16.3.0

**描述遇到的问题**
切换前台激活的窗口后，打字有概率第一个按键（a-z）不进入候选框直接上屏，从第二个开始，后续按键（a-z）正常进入候选框
第一个按键和后续按键是连续输入的，间隔就是正常打字时候的按键间隔

上一个weasel版本0.16.2从来没遇到此类情况

**复现步骤**
重现问题的步骤，如：
1. 切换任意窗口
2. 键入一串按键

后续有更稳定复现方式再更新

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
使用雾凇 小鹤双拼
default.custom.yaml文件如下
```yaml
patch:
  schema_list:
    - {schema: double_pinyin_flypy}
  ascii_composer/switch_key/Shift_L: commit_code
  ascii_composer/switch_key/Shift_R: commit_code
  punctuator/half_shape/$: '$'
  recognizer/patterns/toggle_menu: "^[\\/][0-9A-Za-z]*$"
  recognizer/patterns/url_2: "^[A-Za-z]+[.].*"
```

**截图**

**其他补充说明**
如果有其他补充说明，可以写在这里
