### ISSUE TITLE
vim-mode开启，gvim切换到NERDTree树时会变成中文输入法

### ISSUE THREAD

**Issue by 1030504258** [rime/weasel#1431]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本

**操作系统信息**
 - OS 详细版本: [ Windows 10 21H2 19044.5011]
 - 小狼毫版本: [ 0.16.3 ]

**描述遇到的问题**
vim-mode开启，gvim切换到NERDTree树时会变成中文输入法

**复现步骤**
![Snipaste_2024-11-16_23-50-30](https://github.com/user-attachments/assets/471c501d-731a-4ace-a6ab-40efb4f25e2c)

**预期行为**
gvim切换到NERDTree树时保持英文或自动转成英文

**用户文件**

```yaml
# weasel.custom.yaml
patch:
  # 针对个别应用单独配置选项
  app_options/gvim.exe:
    vim_mode: true
    ascii_mode: true
  app_options/sublime_text.exe:
    ascii_mode: true
    vim_mode: true
  app_options/code.exe:
    ascii_mode: true
    vim_mode: true
  app_options/phpstorm64.exe:
    ascii_mode: true
    vim_mode: true
```
