### ISSUE TITLE
win11 24h2 最新正式版 任务栏图标无法隐藏问题

### ISSUE THREAD

**Issue by Noachlu** [rime/weasel#1432]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 weasel 下载
- [x] 我在使用小狼毫的最新发布版本

**操作系统信息**
 - OS 详细版本: [ Windows 11 24H2 26100.2314]
 - 小狼毫版本: [ 0.16.3.0]

**描述遇到的问题**
在之前可以通过weasel.custom.yaml文件的`display_tray_icon: false`代码来关闭任务栏图标显示，但是更新到24h2最新版之后便失效了。该文件代码如下：
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  generator: "Weasel::UIStyleSettings"
  modified_time: "Fri Oct  4 23:02:30 2024"
  rime_version: 1.11.2

patch:
  style:
    color_scheme: noachlu
    font_face: 苹方
    font_point: 16
    horizontal: true
    inline_preedit: true
    display_tray_icon: false
    label_format: "%s."
    layout:
      min_width: 100
      min_height: 0
      border_width: 1
      margin_x: 8
      margin_y: 8
      spacing: 10
      candidate_spacing: 16
      hilite_spacing: 3
      hilite_padding: 3
      round_corner: 10
```
**截图**
![image](https://github.com/user-attachments/assets/f89dd4d4-29b7-4696-a37e-45688b00109c)
