### ISSUE TITLE
小狼毫和Kate文本编辑器似乎有点不兼容

### ISSUE THREAD

**Issue by hexawing** [rime/weasel#1436]
**上报前请检查**
- [V] 我遇到的问题没有其他人在 issue 里提到过
- [V] 我的小狼毫版本于 rime/weasel 下载
- [V] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows10 22H2 内部版本19045.5131
 - 小狼毫版本: 0.16.3.0

**描述遇到的问题**
我打五笔，配置好无重码时四码自动上屏，以及有重码时继续打下一个词时重码的第一候选自动上屏。
在大部分软件下都工作正常，但在Kate文本编辑器下表现不太对。

**复现步骤**
重现问题的步骤，如：
1. 打开 Kate 软件（版本23.04.01）
2. 输入任意有五笔重码的文字，比如“输入”
3. 无视当前的候选文字继续输入，比如“if”（“法”字的五笔编码）
4. 文本显示成【|输入】，其中竖线表示光标
5. 如果输入空格让“法”字上屏，那么文本显示成【法|输入】，其中竖线表示光标

**预期行为**
第4步时，应该显示文本为【输入|】，其中竖线表示光标
第5步时，应该显示文本为【输入法|】，其中竖线表示光标

**用户文件**
五笔wubi86.schema.yaml
```
# Rime schema settings
# encoding: utf-8

schema:
  schema_id: wubi86
  name: "五笔86"
  version: "0.21"
  author:
    - 發明人 王永民先生
  description: |
    五筆字型86版
    碼表源自 ibus-table
    敲 z 鍵進入拼音反查
  dependencies:
    - pinyin_simp
```

wubi86.custom.yaml
```
patch:
  punctuator: # 设置标点符号集
    import_preset: symbols
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase #自定义词组的位置，在外面的同名.txt文件
    db_class: stabledb
    enable_completion: false
    enable_sentence: true
    initial_quality: 1

  speller:
    max_code_length: 4 # 最长4码
    auto_select: true # 4码完成无重码自动上屏
    auto_select_unique_candidate: true # 在4码出候选的情况下继续打字会将第一词条上屏（但是在某些软件里有bug，上屏是上屏了，但光标不会走。比如Kate）

```
![9c4fc63eae8851e4ff9153ce0caf9611](https://github.com/user-attachments/assets/7f71d507-7eff-45a7-b16b-aef439b09d49)
