### ISSUE TITLE
候选栏交互UI优化建议

### ISSUE THREAD

**Issue by AlightYoung** [rime/weasel#1442]
**上报前请检查**
- [✔] 我遇到的问题没有其他人在 issue 里提到过
- [✔] 我的小狼毫版本于 rime/weasel 下载
- [✔] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 24H2 26100.2454
 - 小狼毫版本: 0.16.3

**描述遇到的问题**
在使用参数 `mark_text: ""`的情况下（hilited_mark_color 非透明色），会出现类似Windows 11输入法类似的候选项高亮标识符，在使用上下键切换候选字时，会出现文字的移动。（Windows 11输入法似乎没有这个问题）

**复现步骤**
启动weasel-0.16.3，配置雾凇拼音并启用，修改weasel配置（具体修改有点记不清，主要是调整了一些样式的布局和新增一个win11的颜色模板并应用，weasel.yaml在下方用户文件补充），使用拼音打字并通过上下键观察失去高亮的候选项的文字左右移动现象。

感觉可能是高亮标识符作为候选项文字内容被转移后候选项宽度变化带来的显示问题，该问题并不影响输入法的正常使用，但是如果能优化成win11默认输入法的效果会更美观一些。

**预期行为**
win11默认输入法在切换高亮候选项时的文字位置固定效果。

**用户文件**
weasel.yaml(删除了若干preset_color_schema以及一些注释后)

```yaml
# 部分选项需要将 Weasel 更新 16.0 及以上版本才能生效
config_version: "2024-09-25"

# [app_options]
# 针对特定应用的设置
app_options:
  firefox.exe:
    inline_preedit: true   # 行内显示预编辑区：规避 <https://github.com/rime/weasel/issues/946>
# [End of <app_options>]

# [global settings]
show_notifications: true                   # 是否显示状态变化的通知：true；false；option_list（方案内的开头 option）
show_notifications_time: 1200              # 通知显示的时间，单位 ms
global_ascii: false                        # 切换为 ascii 模式时，是否影响所有窗口：true；false
# [End of <global settings>]

# [style]
# 字体；候选项、候选窗口的行为、布局及样式
style:
  color_scheme: purity_of_form_custom      # 默认配色方案
  # color_scheme_dark: nord                # 深色模式下，Weasel 的配色方案，Windows 10 1809+ 可用

  # 全局字体
  # 格式：字体1:起始码位:结束码位:字重:字形,字体2……，字体会依次 fallback
  # 详细设定请参考 <https://github.com/rime/weasel/wiki/字體設定>
  font_face: "Segoe UI Emoji, Microsoft YaHei, SF Pro, Noto Color Emoji"
  label_font_face: "Microsoft YaHei"       # 标签字体
  comment_font_face: "Microsoft YaHei"     # 注释字体
  font_point: 14                           # 全局字体字号
  label_font_point: 14                     # 标签字体字号，不设定 fallback 到 font_point
  comment_font_point: 14                   # 注释字体字号，不设定 fallback 到 font_point

  inline_preedit: true                     # 行内显示预编辑区：true；false
  preedit_type: composition                # 预编辑区内容：composition（编码）； preview（选中的候选）；preview_all（全部候选）

  fullscreen: false                        # 候选窗口全屏显示：true；false
  horizontal: true                         # 候选项横排：true；false
  vertical_text: false                     # 竖排文本：true；false
  # text_orientation: horizontal           # 文本排列方向，效果和 `vertical_text` 相同：horizontal；vertical
  vertical_text_left_to_right: false       # 竖排方向是否从左到右：true；false
  vertical_text_with_wrap: false           # 文本竖排模式下，自动换行：true；false
  vertical_auto_reverse: false             # 文本竖排模式下，候选窗口位于光标上方时倒序排列：true；false

  label_format: "%s"                       # 标签字符：例如 %s. 效果为 1. 2. 3. ....
  mark_text: ""                            # 标记字符，显示在选中的候选标签前，需要在配色方案中指定颜色；如该项为空字符串 "" 而配色方案中 hilited_mark_color 非透明色，则显示 Windows 11 输入法风格标记
  ascii_tip_follow_cursor: false           # 切换 ASCII 模式时，提示跟随鼠标，而非输入光标
  enhanced_position: true                  # 无法定位候选框时，在窗口左上角显示候选框：true；false
  display_tray_icon: true                 # 托盘显示独立于语言栏的额外图标：true；false
  antialias_mode: default                  # 次像素反锯齿设定：default；force_dword；cleartype；grayscale；aliased
  candidate_abbreviate_length: 30          # 候选项略写，超过此数字则用省略号代替。设置为 0 则不启用此功能
  mouse_hover_ms: 0                        # ! 已弃用。鼠标悬停选词响应时间（ms），设置为 0 时禁用该功能
  hover_type: semi_hilite                         # 鼠标在候选窗口悬停时：none（无动作）；hilite（选中鼠标下的候选）；semi_hilite（高亮鼠标下的候选）

  paging_on_scroll: true                   # 在候选窗口上滑动滚轮的行为：true（翻页）；false （选中下一个候选）
  click_to_capture: false                  # 鼠标点击候选项，创建截图：true；false

  layout:
    baseline: 0                            # 字号百分比，与 linespacing 一同设置可解决字体跳动问题，设置为 0 为禁用
    linespacing: 0                         # 字号百分比，参考 <https://github.com/rime/weasel/pull/1177>
    align_type: center                     # 标签、候选文字、注解文字之间的相对对齐方式：top ; center ; bottom
    max_height: 600                        # 候选框最大高度，文本竖排模式下如高度超此尺寸则换列显示候选，设置为 0 不启用此功能
    max_width: 0                           # 候选框最大宽度，horizontal 布局如宽超此尺寸则换行显示候选，设置为 0 不启用此功能
    min_height: 0                          # 候选框最小高度
    min_width: 10                          # 候选框最小宽度
    border_width: 2                        # 边框宽度；又名 border
    margin_x: 10                            # 主体元素和候选框的左右边距；为负值时，不显示候选框
    margin_y: 10                            # 主体元素的上下边距；为负值时，不显示候选框
    spacing: 130                            # inline_preedit 为否时，编码区域和候选区域的间距
    candidate_spacing: 14                  # 候选项之间的间距
    hilite_spacing: 4                      # 候选项和相应标签的间距
    hilite_padding: 8                      # 高亮区域和内部文字的间距，影响高亮区域大小
    # hilite_padding_x: 8                  # 高亮区域和内部文字的左右间距，如无特殊指定则依 hilite_padding 设置
    # hilite_padding_y: 8                  # 高亮区域和内部文字的上下间距，如无特殊指定则依 hilite_padding 设置
    shadow_radius: 0                       # 阴影区域半径，为 0 不显示阴影；需要同时在配色方案中指定非透明的阴影颜色
    shadow_offset_x: 4                     # 阴影左右偏移距离
    shadow_offset_y: 4                     # 阴影上下偏移距离
    corner_radius: 8                       # 候选窗口圆角半径
    round_corner: 8                        # 候选背景色块圆角半径，又名 hilited_corner_radius
    # type: vertical                       # 布局设置，效果和 style 下的设置相同：
                                           # horizontal（横向）；vertical（竖向） ; vertical_text（竖排文本） ; vertical+fullscreen（全屏） ; horizontal+fullscreen（横向全屏）
# [End of <style>]

# [preset_color_schemes]
# 配色设定
# 在小狼毫用户目录新建 preview 文件夹，将自定义皮肤的截图重命名为 color_scheme_<name>.png 放入此文件夹，可以在「输入法设定」中看到自定义皮肤效果

# 小狼毫配色在线设计：
# [RIME 西米](https://fxliang.github.io/RimeSeeMe/)
# [小狼毫配色详解](https://github.com/rime/weasel/wiki/定制小狼毫配色)

preset_color_schemes:

  win11:
    name: Windows/11
    author: MS
    color_format: rgba
    back_color: 0xFFFFFF
    shadow_color: 0x00000000
    border_color: 0xFFFFFF
    text_color: 0x00000000
    hilited_text_color: 0x000000
    hilited_back_color: 0xF0F0F0
    hilited_shadow_color: 0x00000000
    hilited_mark_color: 0x0067C0
    hilited_label_color: 0x000000
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0x000000
    hilited_candidate_back_color: 0xF0F0F0
    hilited_candidate_border_color: 0x00000000
    hilited_candidate_shadow_color: 0x00000000
    label_color: 0x000000
    candidate_text_color: 0x000000
    comment_text_color: 0x000000
    candidate_back_color: 0x00000000
    candidate_border_color: 0x00000000
    candidate_shadow_color: 0x00000000
    prevpage_color: 0x00000000
    nextpage_color: 0x00000000
# [End of <preset_color_schemes>]
```

**截图**

weasel效果：

https://github.com/user-attachments/assets/6bed4962-2bbc-49df-b67b-1643f377855e

win11默认输入法效果：

https://github.com/user-attachments/assets/8f19573a-6f17-4244-bd7b-c00cad03b34f
