### ISSUE TITLE
每次 windows 重新启动时，候选词框体无法显示。

### ISSUE THREAD

**Issue by aquariuslt** [rime/weasel#1488]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 Version 24H2 (OS Build 26100.2894)
 - 小狼毫版本: 0.16.3.18.9A5244b

**描述遇到的问题**

通过 `weasel.custom.yaml` patch style 后，
每次 windows 重新启动时，候选词框体无法显示。

**复现步骤**
重现问题的步骤，如：

1. 修改 weasel.custom.yaml
```
patch:
  style:
    font_face: "Noto Serif CJK SC" # 主要字体
    font_point: 11 # 主要字体大小
    label_font_point: 11 # 标签字体大小
    comment_font_point: 11 # 注释字体大小
    horizontal: true # 横排显示
    inline_preedit: true # 嵌入式候选窗，单行模式
```
2. 重新部署
3. 候选词框体如下：
![Image](https://github.com/user-attachments/assets/83d6044a-011c-48d7-bd5b-86e265dba66f)
4. 重启 windows
5. 切换到小狼毫输入法
6. 打字，候选框体无法正常展示：

![Image](https://github.com/user-attachments/assets/b37c0354-bbe0-4b93-bfc1-d3fcab87a6fb)

> 目前，为了解决该问题，我自己的临时解决方案是在重启 windows 后。注释 `weasel.custom.yaml` -> 重新部署输入法 -> 还原注释 `weasel.custom.yaml` -> 重新部署输入法

**预期行为**

windows 重新启动时，切换到 小狼毫输入法打字，候选词框框正常显示。

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里
