### ISSUE TITLE
weasel do not show toggle state if simplifier/option_name is not "simplification"

### ISSUE THREAD

**Issue by jack6th** [rime/weasel#1493]
**Describe the bug**
如果simplifier/option_name的值不是"simplification"，在切换时不会提示状态

**To Reproduce**
Steps to reproduce the bug:
1. 选择"明月拼音简化字"方案
2. 按Ctrl+Shift+4切换至繁体
3. 在输入处并没有提示"漢字"，但目前已经是繁体输入状态

**Expected behavior**
在简繁切换时提示"漢字"或"汉字"

**Flavor(please complete the following information):**
Select your flavor:
- [x] Weasel

Package:
- OS: Windows 7 SP1 32bit
- Version: weasel-0.14.3.0, librime 1.13.0

**Additional context**
```
switches:
  - name: simplification
    reset: 0
    states: [ 简体, 繁體 ]
  - name: emoji_suggestion
    reset: 0
    states: [ 文字, 表情 ]

engine:
  ... #略
  filters:
    - simplifier@emoji_suggestion
    - simplifier
    - uniquifier

simplifier:
  option_name: simplification
  opencc_config: s2t.json

emoji_suggestion:
  opencc_config: emoji.json
  option_name: emoji_suggestion
  tips: all

key_binder:
  import_preset: default
  bindings:
    - { when: always, accept: Control+Shift+4, toggle: simplification }
    - { when: always, accept: Control+Shift+dollar, toggle: simplification }
    - { when: always, accept: Control+Shift+5, toggle: emoji_suggestion }
    - { when: always, accept: Control+Shift+percent, toggle: emoji_suggestion }
```
尝试将方案相关部分修改为上方的配置
1. 将 zh_simp 改为 simplification
2. 安装emoji_suggestion （https://github.com/rime/rime-emoji）
按Control+Shift+4，此时会提示"漢字"或"汉字"状态的切换，而不是"简体"或"繁體"
按Control+Shift+5，在切换时仍然不会提示状态，但可以输入表情
