### ISSUE TITLE
指定配色方案时的代码似乎在wiki中有误？

### ISSUE THREAD

**Issue by AnLazyOtter** [rime/weasel#1509]
如图，在顶部示例中，有如下说明：
> 设置系统为深色模式时的配色方案为 `aqua` 

对应的代码为：
```yaml
# weasel.custom.yaml
patch:
  "style/color_theme_dark": aqua
```
问：这个示例中的描述是写错了吧？正确的应该是“color_scheme_dark”。

![Image](https://github.com/user-attachments/assets/0a320c0d-d810-4a84-8702-4c552befae5d)
