### ISSUE TITLE
ctrl+c之后，rime出现奇怪的上屏问题

### ISSUE THREAD

**Issue by oTnTh** [rime/weasel#1519]
![Image](https://github.com/user-attachments/assets/468e960d-6a72-44ff-a66b-8d4e3c17c426)

上图中，我在notepad中Ctrl+C复制了一些文字，切换窗口后试图输入wget，此时第一个字母无法正常上屏，且一直黏在光标上。

此时我如果切到别的窗口再切回来，第一个字母w就会上屏了（这个部分没有录）。

![Image](https://github.com/user-attachments/assets/f54b106a-6546-4d23-be00-a14ced67c4d0)

该问题在我这里可以稳定复现，只是不同程序里的表现不太一样，这个是notepad内部的情况。

--------

出现问题的平台是Windows 11，小狼毫0.16.3。

该问题是突然发生的，之前并没有。

一开始我还以为是自己替换了CI里的rime.dll所导致，后来发现卸载重装release版小狼毫，用户文件只保留最简单的luna_pinyin_simp，问题依旧。

进一步测试，从一个打开微软拼音的窗口复制文本，切到另外一个打开微软拼音的窗口，没有该问题；但是从打开微软拼音的窗口，切到打开rime的窗口，该问题依然会出现。

该问题有点过于诡异了，我想了老半天，最近两天并没有装什么特别的东西。也在机器里找了老半天，没找到什么可疑的进程。

哪位大佬能指点一下，给点思路么，谢谢。

**Comment by fxliang** [comment]
vim mode 相关的样子

**Comment by oTnTh** [comment]
默认的luna_pinyin_simp里没有相关的内容：

```
app_options:
  cmd.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true
  firefox.exe:
    inline_preedit: true
```

随便找个编辑器试了一下，vim_mode不管改成什么，好像都是一样的。

困惑（
