### ISSUE TITLE
在 win10的cmd, powershell, cmder等终端中，app_options设置静默英文无效

### ISSUE THREAD

**Issue by specter119** [rime/weasel#153]
tsf模式

```default
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Intel Corporation RYBDWi35.86A.0365.2017.0704.1050, 2017/7/4
```
`weasel.yaml`中设置其他软件均有效，但是终端这三个软件，以及wsl中，静默英文均无效。

**Comment by Prcuvu** [comment]
在 weasel.custom.yaml 中增加设置：
```yaml
patch:
  "app_options/conhost.exe":
    ascii_mode: true
```
