### ISSUE TITLE
关于Emoji和字体Fallback的问题

### ISSUE THREAD

**Issue by liuxd17thu** [rime/weasel#1531]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: 如 Windows 11 24H2 26100.3194
 - 小狼毫版本: 0.16.3

**描述遇到的问题**
我使用了如下的字体设置：
```yaml
patch:
  style:
    font_face: "Segoe UI Emoji:fe0f:fe0f, Segoe UI Emoji:20e3:20e3, 等距更纱黑体 SC:Light, Segoe UI Emoji"
```

但在输入emoji：1️⃣（编码\ufe0f \u20e3）时，并没有使用Segoe UI Emoji进行渲染，似乎并没有匹配上fe0f的规则，回退到了更纱黑体（请无视更纱黑体这个字形的渲染问题）
![Image](https://github.com/user-attachments/assets/875c51d9-afb0-4c72-bc7c-d4d22ff90403)

作为对比，使用下面的配置：
```
patch:
  style:
    font_face: "Segoe UI Emoji, 等距更纱黑体 SC:Light, Segoe UI Emoji"p
```
![Image](https://github.com/user-attachments/assets/5f37bde9-bb76-40fd-ab19-7c1ea15632e0)
则确实调用了Segoe UI Emoji。
