### ISSUE TITLE
将边框绘制于背景色之上

### ISSUE THREAD

**Issue by 1024th** [rime/weasel#1534]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 版本24H2 (OS内部版本26100.3476)
 - 小狼毫版本: 0.16.3.0

**描述遇到的问题**

将 `margin` 设置为与 `hilite_padding` 相等的值，目前高亮候选字的背景色（hilited_candidate_back_color）会遮盖整个窗体的边框（border_color），如图中蓝色背景色遮盖了灰色边框的一半。如果将灰色边框绘制于蓝色背景色之上会更加美观。

![Image](https://github.com/user-attachments/assets/1b157df6-0362-43e9-b60b-c03a52870151)

这是因为目前所有的矩形框与其相匹配边框都是一同绘制的，于是先绘制了整个窗体的背景和边框，然后在其之上绘制了 hilited_candidate 的背景和边框。
可能需要将以下函数

https://github.com/rime/weasel/blob/4b47310e95c76cfffb0c0828be9563dbb4125aeb/WeaselUI/WeaselPanel.cpp#L477-L577

中的边框绘制拆分出来，并且在

https://github.com/rime/weasel/blob/4b47310e95c76cfffb0c0828be9563dbb4125aeb/WeaselUI/WeaselPanel.cpp#L986-L1006

中调整绘制顺序。

**用户文件**

weasel.custom.yaml

```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Fri Feb 21 15:23:32 2025"
  rime_version: 1.11.2
patch:
  style/+:
    color_scheme: mac_light
    comment_font_point: 10
    font_point: 12
    label_font_point: 12

    layout/+:
      border: 3
      shadow_radius: 6
      shadow_offset_x: 0
      shadow_offset_y: 0
      margin_x: 8
      margin_y: 4
      hilited_corner_radius: 0
      round_corner: 7
      candidate_spacing: 0
      hilite_padding_x: 8
      hilite_padding_y: 4

  preset_color_schemes/+:
    mac_light:
      name: Mac Light
      text_color: 0x404040
      label_color: 0x808080
      back_color: 0xeceeee
      shadow_color: 0x10000000
      border_color: 0xcacaca
      hilited_candidate_text_color: 0xffffff
      hilited_candidate_back_color: 0xcf5737
      candidate_back_color: 0x00000000
```
