### ISSUE TITLE
繁簡切換問題

### ISSUE THREAD

**Issue by delphinuz** [rime/weasel#154]
1.時常要切換繁簡，新版都要選二次(F4->1(漢/半/繁)->3(打繁出簡)，沒有以前F4->4來的方便，主要是漢/半/繁被摺疊到第二選單。

2.第二層選單常常選到的與實際的不同，選第3個打繁出簡，但結果是第2個全型半型。(這應是bug，少1個)。

3. win8.1下無法直接ctrl+shift+4切換繁簡，確定設定檔有以下內容：
```
key_binder:
  bindings:
    - when: always
      accept: Shift+space
      toggle: full_shape
    - when: always
      accept: Control+Shift+4
      toggle: simplification
```
[boshiamy_t.schema.txt](https://github.com/rime/weasel/files/1844984/boshiamy_t.schema.txt)
