### ISSUE TITLE
c2beb41问题更严重了 候选框消失 按 F4 都看不见东西

### ISSUE THREAD

**Issue by wubidao** [rime/weasel#1545]
前几个版本安装后也是出问题，但用16.3.9重新装就会恢复正常。
装了c2beb41，却彻底恢复不了。幸好自己有镜像备份。
我的系统是 win10 LTSB，是最稳定的win10版本。
认真负责些好不好，别拿我们当小白鼠。

**Comment by fxliang** [comment]
未修改ui相关的内容，疑似与你所有的系统关联。目前未复现你所提的问题

**Comment by lotem** [comment]
不能重現的話，可能是配置問題嗎。樓主還原成默認配置試試看？

fxliang ***@***.***> 于2025年3月26日周三 11:56写道：

**Comment by wubidao** [comment]
原来是 佛振大人。
我把我的  weasel.custom.yaml 发给您。
这个皮肤是用官方润笔工具做出来的，但其中2个参数要加上8才行。
记得我的是这样的：
  "style/layout/margin_x": 12 #12
  "style/layout/margin_y": 12 #12
润笔输出的是：
  "style/layout/margin_x": 4
  "style/layout/margin_y": 4
因为 weasel.yaml 默认参数是 8，实际加上 8 才行。
发不了文件，复制代码如下：
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sun Feb 23 21:10:09 2025"
  rime_version: 1.13.1
patch:
  "app_options/EmEditor/ascii_mode": true
  "app_options/chrome/ascii_mode": false
  preset_color_schemes:
    lost_temple: {author: "佛振 <chen.sst@gmail.com>, based on ir_black", back_color: 1978661, border_color: 6710886, candidate_text_color: 11986412, comment_text_color: 11986412, hilited_back_color: 2236962, hilited_candidate_back_color: 316159, hilited_candidate_text_color: 0, hilited_comment_text_color: 0, hilited_label_color: 0, hilited_text_color: 8578762, label_color: 11986412, name: "孤寺／Lost Temple", text_color: 15266806}
  "style/click_to_capture": false
  "style/color_scheme": lost_temple
  "style/comment_font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/comment_font_point": 18 # 18
  "style/display_tray_icon": true
  "style/font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/font_point": 18 # 18
  "style/horizontal": true
  "style/inline_preedit": true
  "style/label_font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/label_font_point": 15  # 15
  "style/layout/border_width": 0
  "style/layout/corner_radius": 11 #11
  "style/layout/hilite_spacing": 4
  "style/layout/margin_x": 12 #12
  "style/layout/margin_y": 12 #12
  "style/layout/round_corner": 11 #11

<img width="695" alt="Image" src="https://github.com/user-attachments/assets/c8974be4-5fef-4143-8d4e-b8ef3dbc5bd7" />

**Comment by wubidao** [comment]
才发现代码复制后怎么变了，重发一遍：
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sun Feb 23 21:10:09 2025"
  rime_version: 1.13.1
patch:
  "app_options/EmEditor/ascii_mode": true
  "app_options/chrome/ascii_mode": false
  preset_color_schemes:
    lost_temple: {author: "佛振 <chen.sst@gmail.com>, based on ir_black", back_color: 1978661, border_color: 6710886, candidate_text_color: 11986412, comment_text_color: 11986412, hilited_back_color: 2236962, hilited_candidate_back_color: 316159, hilited_candidate_text_color: 0, hilited_comment_text_color: 0, hilited_label_color: 0, hilited_text_color: 8578762, label_color: 11986412, name: "孤寺／Lost Temple", text_color: 15266806}
  "style/click_to_capture": false
  "style/color_scheme": lost_temple
  "style/comment_font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/comment_font_point": 18
  "style/display_tray_icon": true
  "style/font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/font_point": 18
  "style/horizontal": true
  "style/inline_preedit": true
  "style/label_font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/label_font_point": 15
  "style/layout/border_width": 0
  "style/layout/corner_radius": 11 #11
  "style/layout/hilite_spacing": 4
  "style/layout/margin_x": 12 #12
  "style/layout/margin_y": 12 #12
  "style/layout/round_corner": 11 #11

**Comment by wubidao** [comment]
代码没变，是网络不畅的原因。

**Comment by wubidao** [comment]
图片是 16.3.9 版和之前的正式版16.3的。

**Comment by lotem** [comment]
快刪了吧。恢復默認的 `weasel.yaml` 看看是否正常顯示。
您自己在調參數做實驗，怎麼能無端指責輸入法軟件拿用戶做實驗呢。

**Comment by wubidao** [comment]
卸载旧版，并把用户文件夹改名。
重新安装最新 night 版，正常了，但重启后候选框要么没有，要么框的背景色和文字色一样。
只能装回 16.3.9  night 版

**Comment by fxliang** [comment]
![Image](https://github.com/user-attachments/assets/06b6234f-e56d-4bfc-85d7-1c0e88b368d7)

用你提供的patch部署的（缩进之类是我手工调整的，你的是不是这样我不知道），未见有什么问题
```yaml
customization:
distribution_code_name: Weasel
distribution_version: 0.16.3
generator: "Weasel::UIStyleSettings"
modified_time: "Sun Feb 23 21:10:09 2025"
rime_version: 1.13.1

patch:
  "app_options/EmEditor/ascii_mode": true
  "app_options/chrome/ascii_mode": false
  preset_color_schemes:
  lost_temple: {author: "佛振 chen.sst@gmail.com, based on ir_black", back_color: 1978661, border_color: 6710886, candidate_text_color: 11986412, comment_text_color: 11986412, hilited_back_color: 2236962, hilited_candidate_back_color: 316159, hilited_candidate_text_color: 0, hilited_comment_text_color: 0, hilited_label_color: 0, hilited_text_color: 8578762, label_color: 11986412, name: "孤寺／Lost Temple", text_color: 15266806}
  "style/click_to_capture": false
  "style/color_scheme": lost_temple
  "style/comment_font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/comment_font_point": 18
  "style/display_tray_icon": true
  "style/font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/font_point": 18
  "style/horizontal": true
  "style/inline_preedit": true
  "style/label_font_face": "方正兰亭中黑_GBK,CJKExtB-G"
  "style/label_font_point": 15
  "style/layout/border_width": 0
  "style/layout/corner_radius": 11 #11
  "style/layout/hilite_spacing": 4
  "style/layout/margin_x": 12 #12
  "style/layout/margin_y": 12 #12
  "style/layout/round_corner": 11 #11
```

未知你系统什么状态无法判断猜测了。
