### ISSUE TITLE
功能需求：请增加输入法初始状态等个性化选项

### ISSUE THREAD

**Issue by softmgr** [rime/weasel#1569]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 24H2
 - 小狼毫版本: 0.16.3.0

**描述遇到的问题**
输入法设置里面只有输入法的选择，太过于简单。对于不同的个性化需求不太友好。
希望增加输入法常用的个性化选项，如：
一、输入法初始状态：
  1.输入开关：打开，关闭。（如果选择关闭，则始终默认英文，需要按Ctrl+space才打开中文输入）
  2.中英标点：中文、英文。
  3.半角全角：半角、全角。
二、候选框样式：坚排、横排。
三、候选框显示个数：1-10。
四、状态栏窗口：显示、隐藏。
五、检索生僻字：检索、不检索、为空码时检索。
六、自定义显示字体：字体和字号选择。

**Comment by cvlot** [comment]
你所描述的这些, 本来就可以自定义啊,  编辑yaml文件, rime的玩法就是可以高度自定义

**Comment by softmgr** [comment]
> 你所描述的这些, 本来就可以自定义啊,  编辑yaml文件, rime的玩法就是可以高度自定义

有没有说明文档呢？

**Comment by cvlot** [comment]
雾凇拼音的博客, 它这里介绍的很明白, https://dvel.me/posts/rime-ice/

**Comment by fxliang** [comment]
https://github.com/rime/weasel/wiki

小狼毫相关的前端设定，参见Wik（如上链接），字体设定可以试用这个 https://github.com/fxliang/weaselfont/releases 的demo预览和检查设定（复制修改weasel.custom.yaml)

至于方案相关的设定，目前没有合适的ui操作方案可以完整兼容全部可以，所以暂无计划的。

**Comment by softmgr** [comment]
> https://github.com/rime/weasel/wiki
> 
> 小狼毫相关的前端设定，参见Wik（如上链接），字体设定可以试用这个 https://github.com/fxliang/weaselfont/releases 的demo预览和检查设定（复制修改weasel.custom.yaml)
> 
> 至于方案相关的设定，目前没有合适的ui操作方案可以完整兼容全部可以，所以暂无计划的。

我实际测试了一下：
大部分功能可以通过yaml配置来实现，有少数根本无法实现：

状态栏窗口，在yaml中加上以下代码后仍然无法显示：
```
patch:
  status_bar:
    show: true
```

初始状态为英文，在yaml中加上以下代码后，它仍然是中文输入为默认：
```
patch:
  ascii_mode: true
```

软键盘，无论如何配置也没有软键盘面板。而如果要配置不同的输入方案来实现特殊字符输入，则不现实，因为用户用的输入法根本就不可能是内置的那几个。可以说是功能缺陷。

快速切换中英文标点、半角全角：因为没有状态栏窗口，所以无法切换。

简体和繁体输入切换：因为没有状态栏窗口，所以无法快速切换，而要重新配置不同的输入方案来切换，这在打字过程中切换是非常不方便的。

**Comment by fxliang** [comment]
隐藏状态栏，有可能是这个里面 有评论中有提及 #1515 

初始化为英文状态，在方案中修改 `switches`下的 `ascii_mode`节点内容参考如下后部署
```yaml
  - name: ascii_mode
    states: ["中", "英"]
    reset: 1
```

或者weasel.custom.yaml中的app_options下增加要默认ascii_mode的app，参考
```yaml
  app_options:
    nvy.exe:
      ascii_mode: true
```

简繁体设定（luna_pinyin)中switches下修改参考
```yaml
  - name: simplification
    states: ["漢字", "汉字"]
    reset: 1
```

全半角标点参考（luna_pinyin)
```yaml
  - name: ascii_punct
    states: ["。，", "．，"]
    reset: 1
```

>  软键盘，无论如何配置也没有软键盘面板。而如果要配置不同的输入方案来实现特殊字符输入，则不现实，因为用户用的输入法根本就不可能是内置的那几个。可以说是功能缺陷。

没有做软键盘界面，使用`punctuator`在方案中实现，可以不同方案不同的leader弹出候选，操作上会比软键盘输入符号更加便捷

![Image](https://github.com/user-attachments/assets/f1ff57dd-7d01-4994-a7f8-cbcff1fcbfcf)

![Image](https://github.com/user-attachments/assets/6576f750-bb73-4439-a5ce-de99c589aec6)
