### ISSUE TITLE
更新至0.17.0.0後在任何我試過的輸入框都打不到字

### ISSUE THREAD

**Issue by tsehygit** [rime/weasel#1595]
**上报前请检查**
- [是] 我遇到的问题没有其他人在 issue 里提到过
- [是] 我的小狼毫版本于 rime/weasel 下载
- [是] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本：Windows 10 1803 17134
 - 小狼毫版本：0.17.0.0

**描述遇到的问题**
更新至0.17.0.0後在任何我試過的輸入框都打不到中文

**复现步骤**
1. 在任何輸入框輸入「a」（倉頡），按空格鍵
2. 輸出「a」

**预期行为**
輸出「日」

**用户文件**
Running duration (h:mm:ss): 0:00:00

core_module.cc:20] registering core components.
registry.cc:14] registering component: config_builder
registry.cc:14] registering component: config
registry.cc:14] registering component: schema
registry.cc:14] registering component: user_config
dict_module.cc:25] registering components from module 'dict'.
registry.cc:14] registering component: tabledb
registry.cc:14] registering component: stabledb
registry.cc:14] registering component: plain_userdb
registry.cc:14] registering component: userdb
registry.cc:14] registering component: corrector
registry.cc:14] registering component: dictionary
registry.cc:14] registering component: reverse_lookup_dictionary
registry.cc:14] registering component: user_dictionary
registry.cc:14] registering component: userdb_recovery_task
gears_module.cc:42] registering components from module 'gears'.
registry.cc:14] registering component: ascii_composer
registry.cc:14] registering component: chord_composer
registry.cc:14] registering component: express_editor
registry.cc:14] registering component: fluid_editor
registry.cc:14] registering component: fluency_editor
registry.cc:14] registering component: key_binder
registry.cc:14] registering component: navigator
registry.cc:14] registering component: punctuator
registry.cc:14] registering component: recognizer
registry.cc:14] registering component: selector
registry.cc:14] registering component: speller
registry.cc:14] registering component: shape_processor
registry.cc:14] registering component: abc_segmentor
registry.cc:14] registering component: affix_segmentor
registry.cc:14] registering component: ascii_segmentor
registry.cc:14] registering component: matcher
registry.cc:14] registering component: punct_segmentor
registry.cc:14] registering component: fallback_segmentor
registry.cc:14] registering component: echo_translator
registry.cc:14] registering component: punct_translator
registry.cc:14] registering component: table_translator
registry.cc:14] registering component: script_translator
registry.cc:14] registering component: r10n_translator
registry.cc:14] registering component: reverse_lookup_translator
registry.cc:14] registering component: schema_list_translator
registry.cc:14] registering component: switch_translator
registry.cc:14] registering component: history_translator
registry.cc:14] registering component: simplifier
registry.cc:14] registering component: uniquifier
registry.cc:14] registering component: charset_filter
registry.cc:14] registering component: cjk_minifier
registry.cc:14] registering component: reverse_lookup_filter
registry.cc:14] registering component

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
按鍵盤時輸入法是小狼毫的話會令紀錄檔資料夾瘋狂生成一堆INFO log檔，隨機抽查都是上面的內容，只是時間和threadid不同

**Comment by fxliang** [comment]
请试原装配置，目前我用的配置未发现有类似问题，要定位细节一点与哪个配置相关才有进一步讨论的空间

**Comment by Yotoha0303** [comment]
我也有类似的问题，当我尝试将“weasel.custom.yml”中的样式删除后，我可以正常显示输入候选框，但这会使得我新增的样式消失。

**Comment by fxliang** [comment]
> 我也有类似的问题，当我尝试将“weasel.custom.yml”中的样式删除后，我可以正常显示输入候选框，但这会使得我新增的样式消失。

将客制的修改逐行加上看是哪里出的问题吧

**Comment by Yotoha0303** [comment]
> > 我也有类似的问题，当我尝试将“weasel.custom.yml”中的样式删除后，我可以正常显示输入候选框，但这会使得我新增的样式消失。
> 
> 将客制的修改逐行加上看是哪里出的问题吧

我已经尝试过了，但这是“样式的缓存”问题，在我进行删除、部署，再新增、部署后，它的问题得到了解决。

另外，我发现另外一个问题，即开机后“自定义的部分样式会导致'候选框大小被缩小'，字体和输入框非常紧凑的贴近在一起”。

新问题也是在经过“删除、部署，再新增、部署”后得到解决。

我的测试步骤是：
1、重新开机，输入内容时，发现样式问题。
2、删除“weasel.custom.yml”中的样式，再进行部署。
3、新增“weasel.custom.yml”中的样式，再进行部署。
4、空白样式得到解决；候选框大小缩放问题被解决。

目前情况：
我正在尝试使用bat来解决上述bug，并将它添加到开机启动项中。

rime版本：v0.16

备注：我是新版回退，使用旧版本在进行测试

**Comment by fxliang** [comment]
> 另外，我发现另外一个问题，即开机后“自定义的部分样式会导致'候选框大小被缩小'，字体和输入框非常紧凑的贴近在一起”。

说明你的自定义设置很有问题

**Comment by Yotoha0303** [comment]
> 说明你的自定义设置很有问题

在清除所有缓存后和重启后，安装了最新版（v0.17)。仅仅在配置了“weasel.custom.yml”后重启电脑，还是发现候选框和字体贴近在一起的情况。

附上weasel.custom.yml中，该文件的所有内容
 ```
// weasel.custom.yml
patch:
  style:
    color_scheme: soft_eye_protection
    inline_preedit: true  # 开启内嵌预编辑，减少候选框闪烁
    font_face: "PingFang SC"  # 推荐字体，macOS 默认支持，Windows 可替换为“微软雅黑”或“思源黑体”
    font_point: 16  # 字体大小，适中以保证清晰
    horizontal: true  # 横排候选框，护眼更直观
    candidate_format: "%c. %@ "  # 候选词格式，简洁显示
    corner_radius: 5  # 候选框圆角，柔和视觉
    border_width: 1  # 边框宽度，细边框减少压迫感
    text_color: 0x333333  # 文本颜色，深灰色，柔和不刺眼
    back_color: 0xF5F5F5  # 背景色，浅灰白，降低对比度
    border_color: 0xD3D3D3  # 边框色，浅灰，统一风格
    hilited_text_color: 0x000000  # 高亮文本色，黑色，清晰但不过于刺眼
    hilited_back_color: 0xA9D3E2  # 高亮背景色，浅蓝色，护眼且醒目
    candidate_text_color: 0x666666  # 候选词颜色，中灰色，柔和
    hilited_candidate_text_color: 0x000000  # 高亮候选词，黑色，清晰
    hilited_candidate_back_color: 0xA9D3E2  # 高亮候选背景，浅蓝色，护眼
    comment_text_color: 0x999999  # 注释颜色，浅灰，降低视觉干扰
```
