### ISSUE TITLE
翻页失效

### ISSUE THREAD

**Issue by xdaniel9** [rime/weasel#1631]
我设置了`[]/;'/,.`三组翻页按键，但是只有`,.`是生效的
default.custom.yaml如下

```
patch:
    schema_list:
        - schema: rime_ice
    menu/page_size: 9
    "key_binder/bindings":
        - { when: paging, accept: minus, send: Page_Up }
        - { when: has_menu, accept: equal, send: Page_Down }
        - { when: paging, accept: bracketleft, send: Page_Up }
        - { when: has_menu, accept: bracketright, send: Page_Down }
        - { when: paging, accept: comma, send: Page_Up }
        - { when: has_menu, accept: period, send: Page_Down }
```
是我的设置有问题吗
