### ISSUE TITLE
中文输入时小键盘数字键的问题

### ISSUE THREAD

**Issue by GoalBlinkcn** [rime/weasel#1638]
目前小键盘数字键在中文输入时选字，按运算符键不上屏，小键盘回车也不上屏。

期望能和其他输入法习惯一样，中文输入时用小键盘时能把数字，运算符，回车直接上屏。目前尝试设置失败了，看看大佬们有没有什么好的方法。

**Comment by lotem** [comment]
目前不支持數字鍵盤。
有待用數字鍵盤的朋友開發。

**Comment by GoalBlinkcn** [comment]
杯具了, 求大佬们搞一下吧

**Comment by yjnu** [comment]
你将数字键盘映射为主键盘不就行了
default.yaml 中添加快捷键
```yaml
  key_binder:
    bindings:
      - { when: composing, accept: KP_0, send: 0 }
      - { when: composing, accept: KP_1, send: 1 }
      - { when: composing, accept: KP_2, send: 2 }
      - { when: composing, accept: KP_3, send: 3 }
      - { when: composing, accept: KP_4, send: 4 }
      - { when: composing, accept: KP_5, send: 5 }
      - { when: composing, accept: KP_6, send: 6 }
      - { when: composing, accept: KP_7, send: 7 }
      - { when: composing, accept: KP_8, send: 8 }
      - { when: composing, accept: KP_9, send: 9 }
      - { when: composing, accept: KP_Add, send: plus }
      - { when: composing, accept: KP_Subtract, send: minus }
      - { when: composing, accept: KP_Multiply, send: asterisk }
      - { when: composing, accept: KP_Divide, send: slash }
      - { when: composing, accept: KP_Decimal, send: period }
      - { when: composing, accept: KP_Enter, send: Return }
```
