### ISSUE TITLE
中英文同時輸入、無需按轉換鍵是否可行？

### ISSUE THREAD

**Issue by hhtmp88** [rime/weasel#172]
各位：

在香港 ，中文及英文 夾雜輸入 是非常普遍的現像，例如說： "David, 陳大文這個非常好, 愛助人，really a nice guy”

所以很想知道
中英文同時輸入、無需按轉換鍵是否可行？

如果
(a) 編碼輸入鍵：只需使用「7、8、9」三個數字鍵

(b) 選字鍵只用：1-6，六個數字鍵

假設輸入法的名稱是 "ime", ime.yaml 應如何設定令輸入鍵及選字鍵可以按以上的分配使用1-9的數字鍵？

謝謝指教！

**Comment by hhtmp88** [comment]
更正：
==========
假設輸入法的名稱是 "ime", ime.schema.yaml 應如何設定
令輸入鍵 及選字鍵 可以按以上的分配使用1-9的數字鍵？

**Comment by lotem** [comment]
可行。
因爲這個方案只用數字 789 輸入中文編碼，可以讓拉丁字母直接上屏。這就實現了中英文「同時」輸入。
在輸入方案裏設
```yaml
menu:
  page_size: 6
speller:
  alphabet: '789'
```
