### ISSUE TITLE
半角单引号的标点没办法直接commit

### ISSUE THREAD

**Issue by YeLee** [rime/weasel#192]
我在 [punctuator.yaml ](https://github.com/YeLee/configure/blob/master/rime/punctuator.yaml)里面重新绑定了半角单引号的标点

```
punctuator/half_shape:
    "'":  {pair: ["“", "”"]}
```

希望按下【'】时，能直接commit全角双引号。
不知道为什么，重新部署之后，按下【'】，还是弹出输入框。

本以为是pair的原因，换了commit还是这情况，换回系统默认的symbols.yaml也有这问题。
是不是我的[cangjie5.custom.yaml](https://github.com/YeLee/configure/blob/master/rime/cangjie5.custom.yaml)或者其他地方的设置不对？

在Windows和MacOS上都是这情况，不知道有没有办法解决，抑或，这不是BUG，而是程序的一个新特性。

**Comment by lotem** [comment]
默认配置没这回事。应该是自定义配置导致的。
部署后注意检查错误信息。
原题里面用了 `\`。分隔路径中的节点应该要用 `/`。

**Comment by YeLee** [comment]
这个好像不是自订配置的问题。
我把自订配置删掉后，又重新安装小狼毫，初始状态的cangjie5输入法就是没办法直接commit。
在另外一台机子上，鼠须管也是这样，不知道是不是cangjie5.dict.yaml或者cangjie5.schema.yaml有问题哪里跟单引号有冲突来着

**Comment by YeLee** [comment]
查出来了，问题出现在[rime-cangjie/cangjie5.schema.yaml](https://github.com/rime/rime-cangjie/blob/master/cangjie5.schema.yaml)里面
把反查那句代码调整一下，好像这问题就没再出现了 :-)
```
reverse_lookup: "`[a-z]*'?$|[a-z]+'$"
```

**Comment by lotem** [comment]
果然如此。
改好了。

設計的用法是這樣的：
`` `pin'yta（卜廿日） `` 一段反查以 `` ` `` 開始，以 `'` 結束，在 `'` 之後可以接倉頡碼。實現兩種編碼的臨時轉換。
`[a-z]+'$` 是爲了繼續反查下一個拼音：`` `pin'yin'shu'ru' `` 或者不用前導 `` ` ``，輸完拼音再進入反查。

**Comment by YeLee** [comment]
感謝公子，現在終於可以直接上屏引號了 :-)
我說的沒辦法分詞，是說：
我用「dm'doo」輸入「本來」，上屏後會變成「本“來」
就是在正常模式下，「'」本應用作分詞符號的，Librime把牠當作標點來處理了
用「`ben'doo」來輸入「本來」2字卻沒出現這種情況 :-(

**Comment by lotem** [comment]
@YeLee 現在配置改了，不再用 `'` 分詞了，而用作後置的拼音反查標記（因爲用 `'` 切分音節是從拼音過來的習慣），所以 `pin'yin'` 這樣的當作拼音轉換，`oiar;grmbc` 這樣的當作倉頡碼。你覺得怎樣。

**Comment by YeLee** [comment]
還好，僅是多了個記憶符號，慢慢習慣就是

**Comment by xianghongai** [comment]
五笔中存在同样问题，

```yaml
# wubi_pinyin.schema.yaml
speller:
  delimiter: " ;'"
  #max_code_length: 4  # 四碼頂字上屏

#...

reverse_lookup:
  dictionary: pinyin_simp
  prefix: "`"
  suffix: "'"
  tips: 〔拼音〕
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

# ...

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*'?$"
```

```yaml
# symbols.custom.yaml
punctuator:
  half_shape:
    "'": {pair: ["‘", "’"]}
    "\"": {pair: ["“", "”"]}
```
