### ISSUE TITLE
请问可以设置成在任何地方默认英文状态吗？

### ISSUE THREAD

**Issue by yilksd** [rime/weasel#20]
就是不记忆这个输入框之前是什么状态，任何时候定位到一个输入框都是英文状态，需要时按shift切换成中文。请问可以做到吗？怎么操作？

**Comment by jixiuf** [comment]
# 修改默认输入法的状态
  # wubi_pinyin.schema.yaml. 里有个reset: 奖0 改成1 就变成默认英文输入状态
```
switches:
  - name: ascii_mode
    reset: 0  //here it is <---------------------------------------------
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: extended_charset
    states: [ 常用, 增廣 ]
  - name: ascii_punct
    states: [ 。，, ．， ]

```

**Comment by lotem** [comment]
答曰可以。

對 @jixiuf 回答的補充：
``` yaml
# 補丁文件的寫法
# 設輸入方案裏 {name: ascii_mode} 在 switches: 列表中爲第一項，即下標 0
patch:
  switches/@0/reset: 0
```
