### ISSUE TITLE
添加词库，重新部署后，没有更新词库bin

### ISSUE THREAD

**Issue by xinmu99** [rime/weasel#212]
win10 , weasel0.11.0

添加词库成功一次
extended 再添加import词库table后，重新部署 无效

AppData\Roaming\Rime\build\
只有luna_pinyin_simp.schema.yaml更新了，词库bin没有更新
```
__build_info:
  rime_version: 1.3.1
  timestamps:
    default: 1523121152
    default.custom: 1524486194
    luna_pinyin_simp.custom: 1524489094
    luna_pinyin_simp.schema: 1523121150

translator:
  dictionary: luna_pinyin.extended
```
