### ISSUE TITLE
无法通过编辑 *.custom.yaml 的方式修改输入法配置

### ISSUE THREAD

**Issue by duoduoeeee** [rime/weasel#226]
如题。之前可以通过在用户目录中编辑 xxx.custom.yaml 的方式修改 rime 的设置，但现在在 0.11 版中无法再这样修改设置，只能在 xxx.yaml 中硬改，改完之后部署。

话说现在新版的小狼毫好用多了 感谢开发者的努力

**Comment by duoduoeeee** [comment]
windows10 build 17134.48 x64

**Comment by nameoverflow** [comment]
不存在这样的修改，是用户的操作步骤问题……

**Comment by duoduoeeee** [comment]
不太明白额。。那应该怎么改

**Comment by duoduoeeee** [comment]
是 我放在用户文件夹了 不是里面那个build

default.custom.yaml:

```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.11.1
  generator: "Rime::SwitcherSettings"
  modified_time: "Thu May 10 17:26:15 2018"
  rime_version: 1.3.0
patch:
  schema_list:
    - {schema: luna_pinyin}
    - {schema: luna_pinyin_simp}
    - {schema: double_pinyin_flypy}
  switcher:
    abbreviate_options: true
    caption: "〔方案选单〕"
    fold_options: true
    hotkeys:
      - "Control+grave"
      - "Control+Shift+grave"
      - F4
    option_list_separator: " · "
```
