### ISSUE TITLE
同码单字和词组间词频调整失效

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#24]
版本：commit 62fba4f06717701c167cb2584793263300cd17fd
在第三方提供的山人方案中，bdba对应词组“明白”和单字“㿢”。“明白”的词频远高于“㿢”。当打出单字“㿢”一次后，候选框中“㿢”就永远位于“明白”上方，无法手动调回来。
在小狼毫0.9.30发行版和ibus-rime中不存在这个问题。

**Comment by lotem** [comment]
會不會方案裏啓用了新開發的「單字優先」過濾器 `single_char_filter`

**Comment by Prcuvu** [comment]
确认没有启用。这是方案的完整代码：
```
custom_phrase:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 0
  user_dict: custom_phrase
customization: 2533496964
engine:
  filters:
    - simplifier
    - uniquifier
    - "reverse_lookup_filter@pinyin_reverse_lookup"
    - "reverse_lookup_filter@jyutping_reverse_lookup"
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - "affix_segmentor@pinyin"
    - "affix_segmentor@jyutping"
    - "affix_segmentor@pinyin_lookup"
    - "affix_segmentor@reverse_lookup"
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - "script_translator@pinyin"
    - "script_translator@jyutping"
    - "script_translator@pinyin_lookup"
    - "script_translator@jyutping_lookup"
    - reverse_lookup_translator
    - "table_translator@custom_phrase"
jyutping:
  closing_tips: "【山人】"
  dictionary: jyutping
  enable_charset_filter: true
  initial_quality: 0.1
  prefix: J
  suffix: ";"
  tag: jyutping
  tips: "【粵拼】"
jyutping_lookup:
  closing_tips: "【山人】"
  dictionary: jyutping
  prefix: "`J"
  suffix: ";"
  tag: jyutping_lookup
  tips: "【粵拼反查】"
jyutping_reverse_lookup:
  dictionary: sunman
  overwrite_comment: true
  tags:
    - jyutping_lookup
key_binder:
  import_preset: default
menu:
  page_size: 5
pinyin:
  closing_tips: "【山人】"
  dictionary: pinyin_simp
  enable_charset_filter: true
  initial_quality: 0.2
  preedit_format:
    - "xform/([nl])v/$1ü/"
    - "xform/([nl])ue/$1üe/"
    - "xform/([jqxy])v/$1u/"
  prefix: P
  suffix: ";"
  tag: pinyin
  tips: "【拼音】"
pinyin_lookup:
  closing_tips: "【山人】"
  dictionary: pinyin_simp
  preedit_format:
    - "xform/([nl])v/$1ü/"
    - "xform/([nl])ue/$1üe/"
    - "xform/([jqxy])v/$1u/"
  prefix: "`P"
  suffix: ";"
  tag: pinyin_lookup
  tips: "【拼音反查】"
pinyin_reverse_lookup:
  dictionary: sunman
  overwrite_comment: true
  spelling_hints: true
  tags:
    - pinyin_lookup
punctuator:
  import_preset: symbols
recognizer:
  import_preset: default
  patterns:
    jyutping: "(?<!`)J[a-z']*;?$"
    jyutping_lookup: "`J[a-z]*;?$"
    pinyin: "(?<!`)P[a-z']*;?$"
    pinyin_lookup: "`P[a-z]*;?$"
    punct: "^/[0-9]?[a-z]*$"
    reverse_lookup: "`[a-z]*;?$"
reverse_lookup:
  closing_tips: "【拼音】"
  extra_tags:
    - pinyin_lookup
    - jyutping_lookup
  prefix: "`"
  suffix: ";"
  tag: reverse_lookup
  tips: "【反查】"
schema:
  author:
    - "谢振斌"
  dependencies:
    - pinyin_simp
    - luna_pinyin
    - jyutping
  description: |
    山人全息码
    sunman.uueasy.com
    
  name: "山人"
  schema_id: sunman
  version: 0.9.01
simplifier:
  option_name: sunman_simp
  tips: all
speller:
  algebra:
    - "fuzz/^(\\w)(\\w).+$/$1$2/"
    - "fuzz/^(\\w)(\\w)(\\w).+$/$1$2$3/"
    - "fuzz/^(\\w)(\\w)(\\w)(\\w).+$/$1$2$3$4/"
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
style:
  horizontal: false
switches:
  - name: ascii_mode
    reset: 1
    states: ["中文", "西文"]
  - name: full_shape
    states: ["半角", "全角"]
  - name: ascii_punct
    states: ["。，", "．，"]
  - name: sunman_simp
    states: ["漢字", "汉字"]
translator:
  dictionary: sunman
  enable_user_dict: true
  prism: sunman
  strict_spelling: true
```
