### ISSUE TITLE
app_options应该patch至哪个文件？

### ISSUE THREAD

**Issue by toiiggww** [rime/weasel#245]
版本weasel-0.11.1，weasel.yaml中如下配置不再起作用
app_options:
  cmd.exe:
    ascii_mode: true

**Comment by xuchengpeng** [comment]
```
patch:
  app_options/emacs.exe:
    ascii_mode: true
  app_options/emacsclient.exe:
    ascii_mode: true
```
