### ISSUE TITLE
添加了 symbol 之后, 中英文标点之间无法正常切换

### ISSUE THREAD

**Issue by chs513** [rime/weasel#251]
```
# wubi_pinyin.custom.yaml
patch: 
    translator/enable_user_dict: false  #关闭词频调整

patch:            
    switches:
      - name: ascii_mode                # 0: 激活小狼毫时, 默认使用的是中文输入法, 而不是英文输入状态
        reset: 0
        states: [ 中文, 西文 ]
      - name: full_shape
        states: [ 半角, 全角 ]
      - name: extended_charset
        states: [ 常用, 增廣 ]
      - name: ascii_punct                # 1: 激活小狼毫时, 默认使用的是英文标点. 默认是用 "Ctrl + ." 切换中英文标点
        states: [ 。，, ．， ]
        reset: 1
        

patch:
    recognizer/patterns/punct: "^/[a-z]*$"      # 用正则表达式指定 "/xx" 为匹配样式, 这样后面的 "/xl" 才会起作用
    punctuator:
        half_shape:
            # '+' : { commit: '+_+' }       # 模板示例:  "+" ==> "+_+"
            # "/": ["/", "、", "／", "÷"]
        symbols:
            '/chs': [ /xl (希腊字母), /xld (希腊字母<大写>), /dx (大写数字), /c (摄氏度) ]     # 特殊格式提示
            '/xl': [ α, β, γ, δ, ε, ζ, η, θ, ι, κ, λ, μ, ν, ξ, ο, π, ρ, σ, ς, τ, υ, φ, χ, ψ, ω ]
            '/xld': [ Α, Β, Γ, Δ, Ε, Ζ, Η, Θ, Ι, Κ, Λ, Μ, Ν, Ξ, Ο, Π, Ρ, Σ, Τ, Υ, Φ, Χ, Ψ, Ω ]
            '/dx': [ 壹, 贰, 叁, 肆, 伍, 陆, 柒, 捌, 玖, 拾, 佰, 仟 ]
            '/c': ℃
```

不加 symbol 的时候, 中英文标点是可以正常切换的.
