### ISSUE TITLE
在默认为英文输入模式下，无法使用ctrl+Space进行中英输入模式转换

### ISSUE THREAD

**Issue by Banyc** [rime/weasel#253]
```
switches:
  - name: ascii_mode
    reset: 0  # 1为默认英文状态，0为默认中文状态
    states: [ 中文, 西文 ]
```

```
  ascii_composer/switch_key:
      Caps_Lock: noop
      Shift_L: noop
      Shift_R: noop
      Control_L: noop
      Control_R: noop
```

但是如果在只改变默认为中文输入的情况下，ctrl+Space反而能够进行中英输入模式转换
