### ISSUE TITLE
反查功能字符编码问题

### ISSUE THREAD

**Issue by royinor** [rime/weasel#312]
reverse_lookup_filter 中，overwrite_comment 为 false 时，若反查结果首个不是英文字母，首个字符会被拆成两个问号

**Comment by chromezh** [comment]
The problem may be more universal than the description.

![moj](https://user-images.githubusercontent.com/32255369/49996622-73700d00-ffca-11e8-8172-d5154b363eab.png)

For example, the problem emerges in the following config:

``` yaml
engine:
  ...
  segmentors:
    ...
    - "affix_segmentor@swiftkana"
    ...
  translators:
    ...
    - "table_translator@swiftkana"
    ...

swiftkana:
  dictionary: swiftkana
  prefix: "W"
  suffix: ";"
  tips: 『仮名』
  tag: swiftkana

...
```

And the file `swiftkana.dict.yaml` looks like:

``` yaml
# Rime dictionary
# encoding: utf-8
---
name: swiftkana
version: "V1.3"
sort: original
use_preset_vocabulary: false
...
あ	あ
い	い
う	う
え	え
お	お
か	か
き	き
...
```

The same problem also happens on trime, so I believe that it is more likely to be the problem of the rime engine.
