### ISSUE TITLE
问一个配置文件格式的问题

### ISSUE THREAD

**Issue by cc9014** [rime/weasel#319]
default.custom.yaml
```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.11.0
  generator: "Rime::SwitcherSettings"
  modified_time: "Tue Apr 10 21:28:06 2018"
  rime_version: 1.3.1
patch:
  schema_list:
    - {schema: emoji}
    - {schema: double_pinyin_flypy}
  key_binder:
    bindings:
      - {when: has_menu, accept: Shift+Tab, send: Page_Up}
      - {when: has_menu, accept: Tab, send: Page_Down}
  "switcher/hotkeys":
    - "Control+grave"
```
上面两个参数用的是- {}，switcher这个只能用引号了？

**Comment by lotem** [comment]
`"switcher/hotkeys":` 的雙引號是可選的。

代碼裏潛在的問題是 `key_binder:` 節點下的所有內容都會被替換，原有的其他 binding 都被覆蓋掉了。
如果用意是追加規則，應定義爲：
```yaml
patch:
  key_binder/bindings/+:
      - {when: has_menu, accept: Shift+Tab, send: Page_Up}
      - {when: has_menu, accept: Tab, send: Page_Down}
```
