### ISSUE TITLE
快捷键「 Ctrl + .」切换「中 / 英」标点失效了吗？

### ISSUE THREAD

**Issue by LeoQtue** [rime/weasel#330]

**Comment by Prcuvu** [comment]
按键绑定的默认配置被重写了，现在需在用户文件夹default.custom.yaml中设置：
```yaml
patch:
  key_binder/bindings/+:
    __include: key_bindings:/windows_compatible_mode_switch
```
