### ISSUE TITLE
设置默认英文输入法补丁失效

### ISSUE THREAD

**Issue by LeoQtue** [rime/weasel#346]
**Windows 10 1809**

情况如下：

- 未设置补丁时，**cmd** 和 **PowerShell** 打开时即为英文输入法

- 但是设置 **vsc** 和 **xshell** 后仍不起作用。

```yaml
# weasel.custom.yaml
patch:
  # 下面的程序默认为英文输入法
  "app_options/Code.exe":
    ascii_mode: true
  "app_options/Xshell.exe":
    ascii_mode: true
```

**Comment by LeoQtue** [comment]
### 刚刚又去翻了下官网资料，发现还是自己马虎了

> [定製指南](https://github.com/rime/home/wiki/CustomizationGuide)（初階）
>
> ### 在特定程序裏關閉中文輸入
>
>```yaml
>【小狼毫】0.9.16 亦開始支持這項設定。
>
>例如，要在 gVim 裏面默認關閉中文輸入，可如此設定：
>
># example weasel.custom.yaml
>
>patch:
>  app_options/gvim.exe:  # 程序名字全用小寫字母
>    ascii_mode: true
>```

#### 忽略了注释中「程序名字全用小寫字母」

另外 **xshell** 还需要加入 **xshellcore.exe** 这个程序才行

最终补丁代码为：

```yaml
patch:
  # 下面的程序默认为英文输入法，
  # !!! 程序名字全用小寫字母 !!!
  "app_options/xshell.exe":
    ascii_mode: true
  "app_options/xshellcore.exe":
    ascii_mode: true
  "app_options/code.exe":
    ascii_mode: true
```
