### ISSUE TITLE
default.custom.yaml中menu/page_size 修改无效

### ISSUE THREAD

**Issue by zhouyisu** [rime/weasel#353]
我的问题是在default.custom中修改其他选项都能够生效（如 我在#307 中所说，可以修改 switcher/caption中的内容，重新部署也能看到改变），但唯独 page_size不能生效。

参照了  #140 和 #226 都没法解决，还望赐教。

default.custom.yaml:

```
patch: 
  "menu/page_size": 9
  "ascii_composer/good_old_caps_lock": true
  "ascii_composer/switch_key/Caps_Lock": clear
  "ascii_composer/switch_key/Control_L": noop
  "ascii_composer/switch_key/Control_R": noop
  "ascii_composer/switch_key/Eisu_toggle": clear
  "ascii_composer/switch_key/Shift_L": clear
  "ascii_composer/switch_key/Shift_R": commit_text
  "switcher/caption": "〔切换〕"
  "switcher/hotkeys": 
    - Control+grave
    - Control+Shift+grave
    - F4
  "switcher/save_options":
    - full_shape
    - simplification
    - extended_charset
  schema_list:
    - schema: luna_pinyin
  switches:
    - name: ascii_mode
    - states: 1
```
