### ISSUE TITLE
重启系统后，输入法候选框变黑

### ISSUE THREAD

**Issue by standin000** [rime/weasel#363]
![image](https://user-images.githubusercontent.com/70658/56500687-78c40200-653e-11e9-89c3-80d13a203e8b.png)

weasel.custom.yaml
```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.13.0
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sun Apr 14 20:31:46 2019"
  rime_version: 1.4.0
patch:
  style/color_scheme: demo
  style/horizontal: true 
  style/inline_preedit: true  # 內嵌編碼（僅支持TSF）
  style/display_tray_icon: true  # 顯示托
```

default.custom.yaml

```

customization:
  distribution_code_name: Weasel
  distribution_version: 0.13.0
  generator: "Rime::SwitcherSettings"
  modified_time: "Sun Apr 14 20:31:17 2019"
  rime_version: 1.4.0
patch:
  schema_list:
    - {schema: luna_pinyin_simp}
    - {schema: luna_pinyin_fluency}
  menu/page_size: 9 
```

**Comment by lotem** [comment]
用戶修改配置使然。

**Comment by standin000** [comment]
> 
> 
> 用戶修改配置使然。

请教我改完配置部署可以，但是重启后不行。如果我要改配置怎么改了？ @lotem

**Comment by lotem** [comment]
不要自己改。用高手配置好的。

**Comment by Ansen** [comment]
> weasel.custom.yaml

```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Wed Apr 15 17:26:21 2020"
  rime_version: 1.5.3
patch:
  "style/color_scheme": google
  "style/horizontal": true # 候選橫排
  app_options/xshell.exe:
    ascii_mode: true
  app_options/xshellcore.exe:
    ascii_mode: true
  app_options/bash.exe:
    ascii_mode: true
  app_options/cmd.exe:
    ascii_mode: true
  app_options/windowsterminal.exe:
    ascii_mode: true
  app_options/code.exe: # vscode
    ascii_mode: true
  app_options/goland64.exe:
    ascii_mode: true
  app_options/pycharm64.exe:
    ascii_mode: true
  app_options/taskmgr.exe: # 任务管理器
  ascii_mode: true
  app_options/explorer.exe: # 资源管理器
  ascii_mode: true
```

> user.yaml

```yaml
var:
  last_build_time: 1601171156
  option:
    full_shape: false
  previously_selected_schema: wubi86
  schema_access_time:
    easy_en: 1591604391
    luna_pinyin: 1596505365
    luna_pinyin_simp: 1606896012
    wubi86: 1606896019
    wubi_pinyin: 1602294639
```

> default.custom.yaml

```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Sun Sep 27 09:44:27 2020"
  rime_version: 1.5.3
patch:
  schema_list:
    - {schema: wubi_pinyin}
    - {schema: luna_pinyin_simp}
    - {schema: easy_en}
    - {schema: wubi86}
  "switcher/hotkeys":
    - F6
```

> wubi86.custom.yaml

```yaml
#Rime Custom settings
#encoding: utf-8

patch:
  speller/max_code_length: 5
  speller/auto_select: true
  # 无重码自动上屏
  speller/auto_select_unique_candidate: true
  # 关闭编码提示
  translator/enable_completion: false
  switches/@0/reset: 0 # 1 默认为英文
  # 使用西文标点
  # 'punctuator/import_preset': alternative
```

> installation.yaml

```yaml
distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.14.3
install_time: "Wed Apr 15 17:25:03 2020"
installation_id: "4323c4d1-9962-4752-9ba1-8e9314092c84"
rime_version: 1.5.3
sync_dir: "D:\\Sync\\OneDrive\\Dropbox\\RimeSync\\weasel"
```


皮肤那块我只改了横排，仍然会出现 1楼说的候选框变黑的问题

比如：我在家远程了 mstsc 公司的电脑，第二天到公司后，就会变黑了，得使用 win+space 切换其它输入法再切换回来才能恢复
