### ISSUE TITLE
在Windows 10 Version 1903更新后候选框界面出现问题

### ISSUE THREAD

**Issue by Gompyn** [rime/weasel#395]
不确定是系统问题还是输入法问题，因为这是在安装更新[KB4502584](https://support.microsoft.com/kb/4502584)、[KB4501375](https://support.microsoft.com/kb/4501375)和[KB4506933](https://support.microsoft.com/kb/4506933)后出现的。

在输入法版本为`Weasel 0.14.2`时候选框变为黑色。更新为`Weasel 0.14.3`后系统缩放设为150%时候选框不跟随系统缩放，大小仍未100%。

<img width="960" alt="批注 2019-06-29 124658" src="https://user-images.githubusercontent.com/29288660/60379809-06a2f880-9a6c-11e9-80c9-5cfcde982241.png">

<img width="960" alt="批注 2019-06-29 124916" src="https://user-images.githubusercontent.com/29288660/60379825-5f729100-9a6c-11e9-80c2-04f01749b294.png">

系统信息：
- 版本：Windows 10 专业版
- 版本号：1903
- 操作系统版本：18362.207

输入法信息：
- weasel.custom.yaml:
``` YAML
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sat Jun 29 11:24:41 2019"
  rime_version: 1.5.3
patch:
  app_options:
    "open-wsl.exe": {ascii_mode: true}
  style:
    color_scheme: brasil
    font_face: "等线"
```

- default.custom.yaml:
``` YAML
patch:
  schema_list:
    - {schema: luna_pinyin}
    - {schema: luna_pinyin_simp}
    - {schema: bopomofo}
    - {schema: cangjie5}
    - {schema: stroke}
    - {schema: terra_pinyin}
    - {schema: emoji}
    - {schema: ipa_xsampa}
    - {schema: sampheng}
    - {schema: zyenpheng}
  "menu/page_size": 7
```

- installation.yaml:
``` YAML
distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.14.3
install_time: "Thu Apr 26 21:16:26 2018"
installation_id: "140acd68-9e9a-4b6f-979d-8b1009487177"
rime_version: 1.5.3
update_time: "Sat Jun 29 11:04:56 2019"
```
