### ISSUE TITLE
英文模式下Shift＋Space不等效于Space

### ISSUE THREAD

**Issue by weyou** [rime/weasel#424]
个人习惯于Ctrl＋Space切换中英文，所以把系统的输入法切换热键修改成了Ctrl＋Shift＋Space以防止冲突。然后在小狼毫里default.custom.ymal定义了使用Ctrl＋Space切换中英文，并且禁用了Shift＋Space键。配置如下：
```
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: commit_code
    Eisu_toggle: clear
  key_binder/bindings:
    - { when: always, accept: Control+space, toggle: ascii_mode }
    - { when: always, accept: Shift+space, send: noop }
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }   
```
然后发现Shift＋space键按下没有反应，正常期望是等效于空格键按下。
所以我修改了上面Shift+Space的定义
`- { when: always, accept: Shift+space, send: space }`
现在中文模式下确实等效于space， 但是英文模式下依然没有反应。我不知道这是否是一个issue，还是我的配置有误。如果要任何时候Shift ＋ Space都等效于Space该怎么做？
