### ISSUE TITLE
bash 的 ascii-mode 不起作用

### ISSUE THREAD

**Issue by ZhuBicen** [rime/weasel#452]
我更改了 `weasel.custom.yml` 文件，更改已经在 `build` 目录中的 `weasel.yaml` 中 patch 成功了。 Visual Studio  Code, Chrome， Windows Cmd 等都可以了，进去默认是英文。但是，git bash,  IDEA,  都不起作用，别的进去之后默认还是中文

`build/weasel.yaml` 中显示：

```
app_options:
  bash.exe:
    ascii_mode: true
  chrome.exe:
    ascii_mode: true
  code.exe:
    ascii_mode: true
  explorer.exe:
    ascii_mode: true
  "git-bash.exe":
    ascii_mode: true
  java.exe:
    ascii_mode: true
```

**Comment by ZhuBicen** [comment]
改为：
```
    conemu64.exe:
      ascii_mode: true
    conemuc64.exe:
      ascii_mode: true
```

后 Cmder 可以了，baseh 还是不可以

Win 10

**Comment by Prcuvu** [comment]
`config_version`为0.21及以上的`weasel.yaml`应该不需要额外设置即在Git Bash中默认开启西文模式。
你的设置可能覆盖了默认的应用列表。请额外为`conhost.exe`添加一条设置。

**Comment by ZhuBicen** [comment]
build 目录下最终为这样，但是 bash.exe 还是默认为中文

```
app_options:
  bash.exe:
    ascii_mode: true
  chrome.exe:
    ascii_mode: true
  cmd.exe:
    ascii_mode: true
  code.exe:
    ascii_mode: true
  conemu64.exe:
    ascii_mode: true
  conemuc64.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true
  explorer.exe:
    ascii_mode: true
  "git-bash.exe":
    ascii_mode: true
  java.exe:
    ascii_mode: true
  "notepad++.exe":
    ascii_mode: true
  "q-dir.exe":
    ascii_mode: true
  taskmgr.exe:
    ascii_mode: true
  youdaodict.exe:
    ascii_mode: true
config_version: 0.22
```
