### ISSUE TITLE
配色方案有问题，有时候出不来样式

### ISSUE THREAD

**Issue by wanglongbiao** [rime/weasel#485]
问题：
我用的是孤寺的皮肤，样式出不来（图1）
这时候注释掉 style 再重新部署（图2），看到样式恢复正常
再取消注释，重新部署，样式就又回来了，一开始怀疑和 inline 属性有关系，后来发现不是

图1:
![1](https://user-images.githubusercontent.com/7327187/77241480-9fe2f200-6c2d-11ea-88b4-b9f6e6a7b16a.jpg)

图2:
![2](https://user-images.githubusercontent.com/7327187/77241481-a40f0f80-6c2d-11ea-9a93-357fb2f3c2a4.jpg)

图3:
![3](https://user-images.githubusercontent.com/7327187/77241484-aa04f080-6c2d-11ea-96c1-da7021d8f2c6.jpg)

我的配置是：
weasel.custom.yaml
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Wed Mar 18 16:22:18 2020"
  rime_version: 1.5.3
patch:
  style:
    color_scheme: lost_temple
    horizontal: true
    display_tray_icon: true
    font_face: "Microsoft YaHei Mono"
    font_point: 12
    inline_preedit: true
```

default.custom.yaml
```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Wed Mar 18 16:20:50 2020"
  rime_version: 1.5.3
patch:
  menu/page_size: 9
  ascii_composer/good_old_caps_lock: true
  schema_list:
    - {schema: double_pinyin}
    - {schema: luna_pinyin_simp}
  ascii_composer/switch_key:
    Shift_L: commit_code
    Shift_R: commit_code
    Caps_Lock: noop
    # Control_L: clear
    # Control_R: commit_text
  key_binder/bindings:
      - {accept: minus, send: Page_Up, when: has_menu}
      - {accept: equal, send: Page_Down, when: has_menu}
      # - {accept: comma, send: Page_Up, when: paging}
      # - {accept: period, send: period, when: paging}
  switcher/hotkeys:
    - "Control+Space"
    - "Control+Shift+F8"
```

double_pinyin.custom.yaml
```
patch:
  # engine/translators:
  #     import_preset: default
  #     - lua_translator@date_translator
  translator/dictionary: wang
  # punctuator:
  #   import_preset: default
  #   full_shape:
  #     "/" : "、"
  #   half_shape:
  #     "/" : "、"
  punctuator:
    import_preset: symbols
    symbols:
      "/fs": [½,‰,¼,⅓,⅔,¾,⅒]
      "/dq": [🌍,🌎,🌏,🌐,🌑,🌒,🌓,🌔,🌕,🌖,🌗,🌘,🌙,🌚,🌛,🌜,🌝,🌞,⭐,🌟,🌠,⛅,⚡,❄,🔥,💧,🌊]
      "/jt": [⬆,↗,➡,↘,⬇,↙,⬅,↖,↕,↔,↩,↪,⤴,⤵,🔃,🔄,🔙,🔚,🔛,🔜,🔝]
      "/sg": [🍇,🍈,🍉,🍊,🍋,🍌,🍍,🍎,🍏,🍐,🍑,🍒,🍓,🍅,🍆,🌽,🍄,🌰,🍞,🍖,🍗,🍔,🍟,🍕,🍳,🍲,🍱,🍘,🍙,🍚,🍛,🍜,🍝,🍠,🍢,🍣,🍤,🍥,🍡,🍦,🍧,🍨,🍩,🍪,🎂,🍰,🍫,🍬,🍭,🍮,🍯,🍼,🍵,🍶,🍷,🍸,🍹,🍺,🍻,🍴]
      "/dw": [🙈,🙉,🙊,🐵,🐒,🐶,🐕,🐩,🐺,🐱,😺,😸,😹,😻,😼,😽,🙀,😿,😾,🐈,🐯,🐅,🐆,🐴,🐎,🐮,🐂,🐃,🐄,🐷,🐖,🐗,🐽,🐏,🐑,🐐,🐪,🐫,🐘,🐭,🐁,🐀,🐹,🐰,🐇,🐻,🐨,🐼,🐾,🐔,🐓,🐣,🐤,🐥,🐦,🐧,🐸,🐊,🐢,🐍,🐲,🐉,🐳,🐋,🐬,🐟,🐠,🐡,🐙,🐚,🐌,🐛,🐜,🐝,🐞,🦋]
      "/bq": [😀,😁,😂,😃,😄,😅,😆,😉,😊,😋,😎,😍,😘,😗,😙,😚,😇,😐,😑,😶,😏,😣,😥,😮,😯,😪,😫,😴,😌,😛,😜,😝,😒,😓,😔,😕,😲,😷,😖,😞,😟,😤,😢,😭,😦,😧,😨,😬,😰,😱,😳,😵,😡,😠]
      "/ss": [💪,👈,👉,👆,👇,✋,👌,👍,👎,✊,👊,👋,👏,👐]
      "/dn": [⌘, ⌥, ⇧, ⌃, ⎋, ⇪, , ⌫, ⌦, ↩︎, ⏎, ↑, ↓, ←, →, ↖, ↘, ⇟, ⇞]
      "/fh": [©,®,℗,ⓘ,℠,™,℡,␡,♂,♀,☉,☊,☋,☌,☍,☑︎,☒,☜,☝,☞,☟,✎,✄,♻,⚐,⚑,⚠]
      "/xh": [＊,×,✱,★,☆,✩,✧,❋,❊,❉,❈,❅,✿,✲]

```
