### ISSUE TITLE
嵌入式候选输入时Word和Outlook出现闪烁问题

### ISSUE THREAD

**Issue by Eason0210** [rime/weasel#538]
目前在Windows 10 下使用小狼毫 0.14.3 遇到一下问题，在Word 和 outlook（Microsoft 365 企业版）中出现闪烁现象，但是在Excel中和Nopad3 以及网页中都没问题。不知道有没有人遇到类似情况，Word中什么地方和Rime冲突了？

![输入闪烁](https://user-images.githubusercontent.com/47546452/86557895-3a233780-bf8a-11ea-810f-6c96cc70470a.gif)

我的weasel.custom.yaml配置如下：

```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Mon Mar 23 09:39:28 2020"
  rime_version: 1.5.3
patch:
  app_options:

  "style/display_tray_icon": true
  "style/horizontal": true #横排显示
  "style/font_face": "微软雅黑"
  "style/font_point": 16 #字体大小
  "style/inline_preedit": true # 嵌入式候选窗单行显示
 
  "style/color_scheme": so_young
```
