### ISSUE TITLE
拼音输入模式下，如何设置使 Shift+字母键 输出的大写字母直接上屏

### ISSUE THREAD

**Issue by yisuixinq** [rime/weasel#559]
如题：拼音输入模式下，如何设置使 Shift+字母键 输出的大写字母直接上屏
我改写了half_shape,还是不行

**Comment by sfcaiz-czx** [comment]
同样的需求 请问有解决方案了吗

**Comment by 1761178412** [comment]
@yisuixinq @sfcaiz1216 
我用的是wubi86方案，在wubi86.custom.yaml中添加以下内容：
```
recognizer:
  # import_preset: default
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    punct: "^/([0-9]0?|[A-Za-z]+)$"
    reverse_lookup: "^z[a-z]*'?$"
    # uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
```

参考：https://www.zhihu.com/question/342476247
