### ISSUE TITLE
Windows 10 下候选字锯齿感严重

### ISSUE THREAD

**Issue by fyears** [rime/weasel#58]
有什么办法解决？换了字体 Microsoft YaHei UI （似乎）毫无作用。

``` yaml
# weasel.custom.yaml
patch:
  style/color_scheme: google
  style/font_face: "Microsoft YaHei UI"
```
