### ISSUE TITLE
如何在首次打开gVim时禁用Rime，而不仅仅是切换ascii 为英文

### ISSUE THREAD

**Issue by VimWei** [rime/weasel#588]
Win10环境下，目前可以实现 在日常使用gVim过程中，从edit模式切换为normal模式时，将Rime的状态切换为禁用状态（使用系統的關閉輸入法功能），且再次进入edit 模式时，重新激活 Rime 并重置ascii状态为中文。

```
# _vimrc
if has("gui_running")
    set imactivatekey=C-space
    inoremap <ESC> <ESC>:set iminsert=2<CR>
endif
```

**但无法实现首次启动gVim时，将输入法切换为禁用状态；而只能实现将输入法的ascii模式从0变为1（英文状态）。**

```
# weasel.custom.yaml
patch:
  app_options/gvim.exe:  # 程序名字全用小寫字母
    ascii_mode: true  # 取消中文状态，方便普通模式下的命令调用
```

而这会导致一个问题：

首次打开gVim的Rime切换逻辑：当在其他软件为Rime激活时，首次打开gVim **（Rime的ascii会根据rime的设置重置为英文状态）** ，并进入编辑模式 **（Rime 的ascii会被 gVim 设置为禁用状态）** ，若此时需要输入中文，只能使用gVim提供的机制Ctrl+^激活中文输入法（或者先切换输入法为其他输入法再切换为Rime），而这与Rime在日常使用gVim情景下的使用逻辑产生不一致，给用户造成困扰。

日常使用gVim时的Rime切换逻辑：取消上述weasel.custom.yaml的patch，并在其他软件为非Rime的英文输入法状态下打开的gVim，并在进入edit模式后手动打开Rime输入法，再切换为normal模式，Rime的ascii状态会被切换为禁用 **（不一致点1：前述为英文状态）** ；当再次进入edit模式时，Rime的ascii状态会被切换为中文 **（不一致点2：前述为禁用状态）** 。

**强烈建议将首次打开gVim和日常使用gVim时的Rime切换逻辑统一起来。**
