### ISSUE TITLE
关于 horizontal 这个配置的位置问题.

### ISSUE THREAD

**Issue by xqin** [rime/weasel#6]
根据Google上面的那些说明, 可以把它以patch的形式设置到
`自己的输入法文案.custon.yaml` 里面,
但我在我的电脑(`Windows 7 x64`)上测试的结果是这个设置放在上面这个yaml里面没效果.
我最终试出来,把它放在 `weasel.custom.yaml` 里面才有效果.

```
  patch:
    style/horizontal: true
```

完整的配置文件为:(`wubi_pinyin.custom.yaml`)

```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.9.24.0
  generator: "Weasel::UIStyleSettings"
  modified_time: "Thu Jul 11 21:48:24 2013"
  rime_version: 0.9.9
patch:
  'style/color_scheme': dark_temple
  style/horizontal: true
  'punctuator/import_preset': alternative
  'key_binder/import_preset': alternative
  ascii_composer/switch_key:
    Shift_L: noop
    Shift_R: commit_code
```

在这里面配置的 界面横向没效果
