### ISSUE TITLE
Win10 开机后界面风格问题

### ISSUE THREAD

**Issue by ASC8384** [rime/weasel#618]
如题，开机后打字成了这样：
![图片](https://user-images.githubusercontent.com/29878345/108790521-e6686b80-75b7-11eb-9219-830b36fad9a4.png)

我在`weasel.custom.yaml`里的配置如下：
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Mon Feb 22 10:37:58 2021"
  rime_version: 1.7.3
patch:
  style:
    color_scheme: psionics
    corner_radius: 5
    font_point: 16
    horizontal: false
    font_face: "思源黑体"
```

需要我将`style`全部注释后重新部署，此时恢复默认，再将注释去掉后重新部署，此时正常显示。

![图片](https://user-images.githubusercontent.com/29878345/108792282-dc486c00-75bb-11eb-93c3-4bae2dfd7bfe.png)

我安装了`MacType`（但是忽略了小狼毫）。
系统是
```
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎2/‎20
操作系统版本	19042.746
体验	Windows Feature Experience Pack 120.2212.551.0
```
