### ISSUE TITLE
定製朙月拼音默認簡化字輸出失敗

### ISSUE THREAD

**Issue by dqwyy** [rime/weasel#64]
看了幫助文檔中的定製指南（初階）中的定製朙月拼音默認簡化字輸出，我試了之後發現了這樣的問題。按照裏面的說明：
```
# luna_pinyin.custom.yaml

patch:
  switches:                   # 注意縮進
    - name: ascii_mode
      reset: 0                # reset 0 的作用是當從其他輸入方案切換到本方案時，
      states: [ 中文, 西文 ]  # 重設爲指定的狀態，而不保留在前一個方案中設定的狀態。
    - name: full_shape        # 選擇輸入方案後通常需要立即輸入中文，故重設 ascii_mode = 0；
      states: [ 半角, 全角 ]  # 而全／半角則可沿用之前方案中的用法。
    - name: simplification
      reset: 1                # 增加這一行：默認啓用「繁→簡」轉換。
      states: [ 漢字, 汉字 ]
```
當我第一次使用的時候，包括打開一個新程序使用，或者是從其他輸入法切換會小狼毫，依然是默認繁體輸出。這個代碼的作用僅僅體現在我切換方案的時候，它纔會變成簡體字，而不是從一開始就是簡體字，請問這個是我自己的問題還是代碼本來的問題，如何解決。因爲我本人在日常簡繁切換比較頻繁，簡體爲主（大約七成），繁體爲輔（大約三成）。所以無奈之下只能用這樣的方式：
```
# luna_pinyin.custom.yaml
patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "英數"]
    - name: full_shape
      states: ["半型", "全型"]
    - name: ascii_punct
      states: ["，。", ",."]
    - name: zh_simp
      reset: 1                # 增加這一行：默認啓用「繁→簡」轉換。
      states: [ 繁體, 简体 ]
  simplifier:
    option_name: zh_simp
```
然後我又習慣用`Ctrl+Shift+F`切換簡繁體（搜狗拼音的習慣），而原來的`simplification`又沒有作用了，只能在把原來的快捷鍵換成這樣：
`    - {accept: "Control+Shift+F", toggle: zh_simp, when: always}`

這樣雖然勉強可以用，但是存在一些問題：
這樣是不是就代表原來的那個幫助文檔說的那種辦法有問題呢？這算是一個Bug麼？有解決的辦法麼？
然後我這樣子用，由於用的是`zh_simp`而不是`simplification`，因此在按快捷鍵裝換繁簡的時候沒有提示，之前用`simplification`是有一個`漢字 中`或者`汉字 中`的提示的。
