### ISSUE TITLE
码表中有句点符号参与编码的字词出现无法自动上屏等问题

### ISSUE THREAD

**Issue by LightAPIs** [rime/weasel#647]
1. 当字词的编码中有 `.` 在中间时候选唯一也无法自动上屏。如编码 `收割  zn.pf`：

![自动上屏](https://cdn.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/20210710205426.gif)

当 `.` 符号在编码末尾时(如编码 `纸片  zxqw.`)就不会有这样的问题，但会出现下面的问题。

2. 当字词的编码中有 `.` 在末尾时重码无法自动顶屏，同时也无法使用数字选择候选项。如编码

```yaml
芯片  eanw.
恐怖片  eanw.
```

![自动顶屏](https://cdn.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/20210710210758.gif)

![选择候选项](https://cdn.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/20210710210846.gif)

---

字母编码以及其他有字符(`; ' , /`)参与的编码正常，不会出现上述问题。方案配置如下：

```yaml
# schema.yaml

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz;',./"
  initials: 'abcdefghijklmnopqrstuvwxyz'
  auto_select: true
```
