### ISSUE TITLE
在default.custom.yaml中, page_size设置无效

### ISSUE THREAD

**Issue by zjhken** [rime/weasel#693]
rime版本1.5.3
重现步骤
1. 在用户文件夹根目录新建新建default.custom.yaml
输入以下内容
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Sun Dec 19 09:44:26 2021"
  rime_version: 1.5.3
patch:
  menu:
    page_size: 8
  schema_list:
    - {schema: chaoqiang_liangbi}
  ascii_composer:
    switch_key:
      Shift_L: commit_code
```
2. 菜单 -> 重新部署
3. 观察`用户文件夹/build/default.yaml`文件, 发和`page_size: 8`, 说明部署生成文件成功
4. 测试Left Shift行为, 确认配置` Shift_L: commit_code`生效
5. 候选词个数仍然为5个, 不生效
