### ISSUE TITLE
候选项竖排选项不生效

### ISSUE THREAD

**Issue by VirgilMing** [rime/weasel#701]
已在`default.custom.yaml`中添加了
```YAML
  patch:
    style/candidate_list_layout: stacked # linear #
    "style/horizontal": false
```
在部署后的`default.yaml`中也有
```YAML
style:
  horizontal: false
```
然而候选项仍是横排。

版本是官方的0.14.3。

怀疑和 #693 可能有关联。

**Comment by lotem** [comment]
爲什麼有 `style/candidate_list_layout`？這個選項不支持的。

默認設置就是豎排。換回出廠設置試試？

**Comment by Ace-Who** [comment]
检查一下方案配置。

**Comment by lotem** [comment]
`default.yaml` 不包含 `style` 選項。

參考 https://github.com/rime/home/wiki/CustomizationGuide#%E5%B0%8F%E7%8B%BC%E6%AF%AB%E5%A4%96%E8%A7%80%E8%A8%AD%E5%AE%9A

**Comment by VirgilMing** [comment]
`weasel.custom.yaml`里我也加了`horizontal:false`

以下是整个文件：
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Thu Jan 20 18:03:50 2022"
  rime_version: 1.5.3
patch:
  style/candidate_list_layout: stacked # linear #
  # style/text_orientation: horizontal # vertical #
  "style/color_scheme": starcraft_ii
  "style/display_tray_icon": false
  "style/font_point": 14
  "style/font_face": "思源宋体"
  "style/horizontal": false
  "style/inline_preedit": true
  "style/layout/border_width": 1
  "style/layout/candidate_spacing": 30
  "style/layout/hilite_padding": 12
  "style/layout/hilite_spacing": 2
  "style/layout/margin_x": 12
  "style/layout/margin_y": 10
  "style/layout/min_height": 0
  "style/layout/min_width": 100
  "style/layout/round_corner": 0
  "style/layout/spacing": 10
  "style/window/@0/move": ""
```
改字体和字号都是生效了的。
