### ISSUE TITLE
上屏时音节间分隔符,能否通过设置取消(就是双拼变换后上屏拼音的不要任何分隔符)

### ISSUE THREAD

**Issue by DouYou-DianShuai** [rime/weasel#714]
你好,我这两天发现了这个输入法,想着上手使用,但在配置的过程中遇到些小问题
由于是新手, 也是刚练习的双拼, 看文档时很多配置对应不上画面, 不过通过文档, 最终也算用上了双拼(用的东风破里下载的双拼自然码),以及一些最基础的配置

如题目那样: 
  通过文档和一些引擎搜索,找到了这个配置: speller/delimiter: 
  当我尝试把 speller/delimiter: false 后,  也确实取消了原本默认的空格间隙
  但是   '上屏变换后输入' 与预期不符合

例如:
  可以这个时候(false),比如 输入  aiyi这个   通过默认的shift+enter 最终上屏的是:  aieningi (直接回车是aiyi)
  我又重新将其设置回(" `"), 输入 aiyi这个   通过默认的shift+enter 最终上屏的是:  ai yi       (直接回车是aiyi)
   我的预期是, 都是  取消掉音节间无任何分隔符,且由双拼变换后的全拼也是符合预期的 (比如这个例子,我就希望得到aiyi )

不知能否有其他策略可以达到这个简单的需求(可能比较奇怪), 可自身确实希望变化后的拼音也是连在一起的

**Comment by 107295472** [comment]
是不是凉了

**Comment by Ace-Who** [comment]
恢复 `speller/delimiter` 的默认设置，这个选项与问题无关，而且它的值应该只能是字符串，不能是布尔值。在补丁文件里作如下配置：

```yaml
# double_pinyin.custom.yaml
patch:
  translator/preedit_format/+:
    - xform/ //
```
