### ISSUE TITLE
key_binder能設置accept組合鍵「Alt」「+」和「Alt」「-」嗎？

### ISSUE THREAD

**Issue by Cyoudgax** [rime/weasel#743]
```
key_binder:
  bindings:
    __patch:
      - when: has_menu
        accept: "Alt+-"
        send: Page_Down
      - when: has_menu
        accept: "Alt++"
        send: Page_Up
```
如上，"Alt++"、"Alt+-"語法錯誤。
