### ISSUE TITLE
教程中 单独fallback_segmentor 不显示输入码

### ISSUE THREAD

**Issue by RJJxp** [rime/weasel#769]
本萌新在慢慢学习rime
RimeWithSchemata 实验教程遇到问题

版本	Windows 10 家庭版
版本号	21H2
安装日期	‎2022-‎2-‎24
操作系统内部版本	19044.2006
体验	Windows Feature Experience Pack 120.2212.4180.0

在 **破空中出鞘** - **开始改装** 部分

```yaml
# ...
schema:
  schema_id: hello
  name: 大家好
  version: "2"

engine:
  processors:
    - fluid_editor
  segmentors:
    - fallback_segmentor
```
使用 fallback_segmentor 后, 应该有的效果是 **显示输入码** -- 空格 -- 上屏

![20220918-140112](https://user-images.githubusercontent.com/22700165/190888363-086be59b-cd6a-4788-9055-841335d4e3c8.gif)

但现在没有显示输入码, 只是 空格 -- 上屏
