### ISSUE TITLE
app_options/exename.exe 不起作用?

### ISSUE THREAD

**Issue by 2anyone** [rime/weasel#79]
```
patch:
  app_options/Notepad2.exe:
    ascii_mode: true
  app_options/sublime_text.exe:
    ascii_mode: true
```

上述设置, notepad2不起作用, 但是sublime_text就没问题, 怎么回事儿呢?

谢谢.
