### ISSUE TITLE
0.14.3_dev_0.95 关闭 color_font 后上屏字码出现锯齿

### ISSUE THREAD

**Issue by dalugm** [rime/weasel#793]
<img width="256" alt="Snipaste_2022-11-05_21-19-11" src="https://user-images.githubusercontent.com/25452934/200121964-5896cb69-15f2-4494-8263-1c6d62c31d3b.png">

如果开启的话打字十分卡手，请问知道是什么原因吗？

<details>
<summary>个人电脑配置如下：</summary>
<pre>
处理器	AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
</pre>
</details>

**Comment by fxliang** [comment]
应该是有其他设定有什么不一样吧？目前在我这边试过设置宋体字似乎一切显示挺好的呀

另外关于彩色字体的卡顿，方便的话贴一下配置。我这边Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz   2.20 GHz 的老电脑都没有卡顿感呀，您这个这么新的电脑性能按说不成问题的。

**Comment by dalugm** [comment]
你好，我刚刚测试了一下，发现换用一个字体就可以解决模糊问题，我之前用的是思源宋体，会出现很明显的锯齿

卡顿问题貌似是因为加载词库的问题，但用 0.14.3 版加载词库一点儿卡顿问题也没有，dev0.95 版本哪怕只加载一个词库打一个字都会卡

相关配置如下：

- weasel.custom.yaml

```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  modified_time: "Sat Oct 29 14:14:20 2022 +0800"
  rime_version: 1.5.3

patch:
  # 這項用於選中下面定義的新方案
  style/color_scheme: luna_white

  # 解决 fxliang 的 fork 版本中的卡顿问题
  # 11/05/22 20:45:26
  style/color_font: false

  #style/horizontal: true         # 候選框是否橫向顯示

  style/corner_radius: 5         # 候选条窗口圆角半径
  #style/hilited_corner_radius: 3 # 高亮候选词圆角半径
  style/border_height: 6         # 窗口边界高度，大于圆角半径才有效果
  style/border_width: 10         # 窗口边界宽度，大于圆角半径才有效果

  style/line_spacing: 4          # 候选词的行间距
  style/spacing: 8               # 内嵌编码与候选词之间的间距
  #style/inline_preedit: true     # 顯示内嵌编码（即首行的拼音，僅支持 TSF）
  #style/preedit_style": preview  # 默認是 composition

  # 候选词文字字体相关
  #style/font_face: "Source Han Sans SC"
  style/font_face: "Source Han Serif SC"
  style/font_point: 12

  # 候选词编号字体相关
  #style/label_font_face: "Source Han Sans SC"
  style/label_font_face: "Source Han Serif SC"
  style/label_font_point: 12

  us_keyboard_layout: true             # 键盘选项：应用美式键盘布局
  show_notifications_when: appropriate # 狀態通知，也可設爲全開（always）全關（never）

  # 針對特定程序進入英文模式
  # Windows 下程序名字全用小寫字母
  app_options/emacs.exe:
    ascii_mode: true
  app_options/gvim.exe:
    ascii_mode: true
  app_options/wt.exe:
    ascii_mode: true
  app_options/msys2.exe:
    ascii_mode: true
  app_options/mingw64.exe:
    ascii_mode: true
  app_options/mingw32.exe:
    ascii_mode: true
  app_options/clang64.exe:
    ascii_mode: true
  app_options/clang32.exe:
    ascii_mode: true
  app_options/clangarm64.exe:
    ascii_mode: true
  app_options/ucrt64.exe:
    ascii_mode: true

  # 在配色方案列表裏加入標識爲 luna_white 的新方案，以下同理
  # 配色方案主要来自 http://zhongguose.com/
  preset_color_schemes/luna_white:
    name: "明月白/Luna White"
    author: "test"
    # 編碼行文字顏色，24 位色值，用十六進制書寫方便些，順序是藍綠紅 0xBBGGRR
    text_color: 0x000000
    # 底色 添加 ee 可以使背景半透明
    # back_color: 0xeeffffff
    back_color: 0xffffff
    # 邊框顏色，與底色相同則爲無邊框的效果
    border_color: 0xcccccc
    # 候選項的序號顏色
    label_color: 0x000000
    # 候選項的文字顏色
    candidate_text_color: 0x000000
    # 候選項提示的顏色，如：顏色`(yan se)'
    # 即爲對 `yan se' 的配色，若未開啓註釋即可
    comment_text_color: 0xb2bbbe
    # 高亮當前候選對應的輸入編碼
    hilited_text_color: 0x000000
    # 高亮候選輸入編碼的底色
    hilited_back_color: 0xffffff
    # 高亮激活候選項的序號顏色
    # 文檔有誤，只有 macOS 下的 Squirrel 支持使用 hilited_candidate_label_color
    # 其他輸入法都應使用 hilited_label_color
    hilited_label_color: 0xffffff
    # 高亮激活候選項的文字顏色
    hilited_candidate_text_color: 0xffffff
    # 高亮激活候選項中的背景顏色
    hilited_candidate_back_color: 0x000000

    # 注：预设的配色方案及代码（指定为 style/color_scheme ）
    #   碧水 - aqua
    #   青天 - azure
    #   暗堂 - dark_temple
    #   明月 - luna
    #   墨池 - ink
    #   孤寺 - lost_temple
    #   暗堂 - dark_temple
    #   曬經石 - solarized_rock
    #   簡約白 - clean_white
```

- luna_pinyin.custom.yaml

```
patch:
  # 載入朙月拼音擴充詞庫
  translator/dictionary: luna_pinyin.extended

  # （注意，此功能只適用於朙月拼音系列方案，不適用於各類雙拼方案）
  # 本條補靪只在「小狼毫 0.9.30」、「鼠鬚管 0.9.25 」、「Rime 1.2」及更高的版本中起作用。
  'speller/algebra/@before 0': xform/^([b-df-hj-np-tv-z])$/$1_/

  # 在未使用 plum（東風破）運行`./rime-install emoji`時
  # 手動添加 emoji 等表情符號支持
  punctuator/import_preset: symbols
  recognizer/patterns/punct: ^/([A-Z|a-z]*|[0-9]|10)$
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
```

- luna_pinyin.extended.dict.yaml

```
---
name: luna_pinyin.extended
version: "2020.04.25"
sort: by_weight                 # 字典初始排序，可选 original 或 by_weight
use_preset_vocabulary: true
# 此處爲朙月拼音擴充詞庫（基本）默認鏈接載入的詞庫
# 如果不需要加載某个詞庫請將其用「#」註釋掉。
# 当前维基版本 20220909
#
# 註：雙拼不支持中英文詞庫（luna_pinyin.cn_en），請用戶手動禁用。

import_tables:
  - luna_pinyin
  - luna_pinyin.biaoqing
  - luna_pinyin.cn_en
  - luna_pinyin.english
  - luna_pinyin.hanyu
  - luna_pinyin.poetry
  - luna_pinyin.wiki
...
```

这是各个词库的大小

![图片](https://user-images.githubusercontent.com/25452934/200152144-dc354c66-5f85-4ea6-bd59-e204b0816556.png)
