### ISSUE TITLE
圓角邊框鋸齒

### ISSUE THREAD

**Issue by ywxt** [rime/weasel#804]
![image](https://user-images.githubusercontent.com/25864091/202855506-627d1ad4-9c0a-4e34-9a17-41c4e2c642fe.png)

選中的候選項，1像素的邊框，和背景色差一大，圓角處就會很明顯。請問這個是程序問題還是我的配置問題？

**Comment by fxliang** [comment]
圆角半径小到一定程度锯齿是不可避免的

你关注的其实应该是圆角处的圆弧不止一个像素的观感吧？

**Comment by ywxt** [comment]
> 圆角半径小到一定程度锯齿是不可避免的
> 
> 你关注的其实应该是圆角处的圆弧不止一个像素的观感吧？

是的，我就是這個意思。

**Comment by fxliang** [comment]
建议改大一点，有时间再看。

**Comment by fxliang** [comment]
@ywxt 可以留意[这个CI结果](https://github.com/fxliang/weasel/actions/runs/3508091058)

**Comment by ywxt** [comment]
![image](https://user-images.githubusercontent.com/25864091/202987824-fc136f57-84ff-4f0d-b044-3976e57b23e4.png)

目前的效果是多了一層邊框，而且陰影也沒了。

**Comment by ywxt** [comment]
```yaml
patch:
  style/color_scheme: win10
  style/horizontal: true
  style/inline_preedit: true
  style/layout/border_width: 1
  # style/layout/border_height: 4      # 窗口上下高度，大于圆角半径才生效                            # 窗口左右宽度，大于圆角半径才生效
  style/layout/candidate_spacing: 4
  style/layout/margin_x: 0
  style/layout/margin_y: 0
  style/layout/min_width: 50
  style/layout/corner_radius: 5
  style/layout/shadow_radius: 5			  #全局阴影模糊半径，如果为0则全局禁用阴影
  style/layout/shadow_offset_x: 0			  #阴影x偏置
  style/layout/shadow_offset_y: 2
  style/layout/hilite_padding: 4
  style/layout/align_type: bottom
  style/font_point: 13
  style/font_face: "霞鹜文楷 TC"
  style/comment_font_face: "霞鹜文楷 TC"
  style/comment_font_point: 10


  
  "preset_color_schemes/win10":  # 在配色方案列表裏加入標識爲 starcraft 的新方案
    name: Windows10
    author: me
    shadow_color: 0xE2E2E2
    text_color: 0x666666             # 編碼行文字顏色，24位色值，用十六進制書寫方便些，順序是藍綠紅0xBBGGRR
    candidate_text_color: 0x000000   # 候選項文字顏色，當與文字顏色不同時指定
    # candidate_shadow_color: 0xE2E2E2  #★非高亮候选阴影色
    back_color: 0xFFFFFF           # 底色
    border_color: 0xE2E2E2           #0xE2E2E2                 # 邊框顏色，與底色相同則爲無邊框的效果
    comment_text_color: 0x6D6D6D      # 拼音等提示文字颜色
    hilited_text_color: 0x000000     # 高亮文字，即與當前高亮候選對應的那部份輸入碼
    # hilited_shadow_color: 0xFFFFFF
    hilited_back_color: 0xFFFFFF     # 設定高亮文字的底色，可起到凸顯高亮部份的作用
    hilited_candidate_text_color: 0xFFFFFF  # 高亮候選項的文字顏色，要醒目！
    hilited_candidate_back_color: 0xCE7539  # 高亮候選項的底色，若與背景色不同就會顯出光棒
    hilited_comment_text_color: 0xEBC6B0     # 注解文字高亮
    # hilited_candidate_shadow_color: 0xCE7539  #★高亮（选中）候选阴影颜色
    hilited_candidate_label_color: 0xfafafa  # 第一候选项编号颜色
```
