### ISSUE TITLE
附STYLE配置，0.14.3_dev_0.98 版本开启COLOR_FONT时非常卡

### ISSUE THREAD

**Issue by soulocker** [rime/weasel#816]
```
patch:
  style:
    horizontal: false                      # 候选框横排
    inline_preedit: true                   # 内嵌模式设置
    preedit_type: preview_all              # composition | preview | preview_all
    show_notifications_when: always        # 状态通知，适当(appropriate)，开（always）关（never）
    display_tray_icon: true
    color_font: true
    
    # 字体名称，从记事本等处的系统字体对话框里能看到
    # THIN, EXTRA_LIGHT, ULTRA_LIGHT, LIGHT, SEMI_LIGHT, NORMAL, REGULAR, MEDIUM, DEMI_BOLD, SEMI_BOLD, BOLD, EXTRA_BOLD, ULTRA_BOLD, BLACK, HEAVY, EXTRA_BLACK, ULTRA_BLACK
    font_face: "思源黑体:NORMAL,Segoe UI Emoji:1f000:1f09f,Noto Color Emoji SVG:80"
    # 字号，只认数字的，不认「五号」、「小五」这样的
    font_point: 14
    comment_font_face: "思源黑体:NORMAL,Segoe UI Emoji:1f000:1f09f,Noto Color Emoji SVG:80"
    comment_font_point: 12
    label_font_face: "思源黑体:NORMAL,Segoe UI Emoji:1f000:1f09f,Noto Color Emoji SVG:80"
    label_font_point: 14
    label_format: " %s "
    mark_text: ""
    capture_type: none
    fullscreen: false
    layout:
      align_type: bottom
      shadow_radius: 1
      shadow_offset_x: 1
      shadow_offset_y: 1
      corner_radius: 10
      border_width: 3
      # 候选字左右边距
      margin_x: 8
      # 候选字上下边距
      margin_y: -1  # 5
      # 候选字背景色色块高度 若想候选字背景色块无边界填充候选框，仅需其高度和候选字上下边距一致即可
      hilite_padding: 8
      # 序号和候选字之间的间隔
      hilite_spacing: 3
      spacing: 10
      # 候选字间隔
      candidate_spacing: 5
      # 候选字背景色块圆角幅度
      round_corner: 3
    color_scheme: BattleShow
  preset_color_schemes:
    BattleShow:
      name: "*****"
      author: "***** <*****>"

      # 候选框
      text_color: 0xffffff
      back_color: 0xcc343e44
      border_color: 0xFD9817
      shadow_color: 0x00000000
      # 未选中候选
      candidate_text_color: 0x5c758f
      candidate_back_color: 0xcc2f383d
      candidate_shadow_color: 0x00000000
      label_color: 0x5c758fW
      comment_text_color: 0x5c758f
      # 被选中预览？
      hilited_text_color: 0x1841dd
      hilited_back_color: 0x120f1f
      hilited_shadow_color: 0x00000000
      # 被选中候选
      hilited_candidate_text_color: 0xffffff
      hilited_candidate_back_color: 0x1841dd
      hilited_candidate_shadow_color: 0x20000000
      hilited_comment_text_color: 0xffffff
      hilited_mark_color: 0xffCC6600
  # 指定程序的默认输入法，匹配不区分大小写
  app_options:
    windowsterminal.exe:
      ascii_mode: true
    powershell.exe:
      ascii_mode: true
    code.exe:
      ascii_mode: true
    putty.exe:
      ascii_mode: true
    listary.exe:
      ascii_mode: true
```

于是乎，我现在有两个选择：
1）关闭COLOR_FONT，看灰白表情，毋宁死！！！
2）开启COLOR_FONT，隐藏候选框，使用PREVIEW_ALL特性（不得不说），很酷，但不容易看清。

另外说一嘴，这个版本附带的RIME会导致OPENCC找不到配置，换旧版1.53rime.dll可解决问题；
但是1.53版我很多LUA脚本无法正常运作，能否提供一个完美的rime.dll呢，希望是win平台下，嵌入了最新的librime-lua：）

附系统信息

![Snipaste_2022-12-26_19-19-59.png](https://war-station-1313844966.cos.ap-guangzhou.myqcloud.com/Snipaste_2022-12-26_19-19-59.png)
