### ISSUE TITLE
0.14.3_dev_0.98 版本 部分程序上屏字体异常

### ISSUE THREAD

**Issue by wxyzh** [rime/weasel#824]
使用 0.14.3_dev_0.98  在win11 22h2 上 部分程序上屏字体异常

具体现象为：
在系统自带记事本、微信PC版、word outlook 365 中输入中文时，上屏的字体为MingLiU 而非系统默认字体

**Comment by fxliang** [comment]
未复现问题
设定是怎样的？
系统字体是怎样定义的？

如果完全没有设定的情况，在我的系统上面回退到的是宋体（Windows 简体中文系统）


> 使用 0.14.3_dev_0.98 在win11 22h2 上 部分程序上屏字体异常
> 
> 具体现象为： 在系统自带记事本、微信PC版、word outlook 365 中输入中文时，上屏的字体为MingLiU 而非系统默认字体

**Comment by wxyzh** [comment]
@fxliang  感谢测试 

配置文件如下：
```
style:
    color_scheme: psionics
    display_tray_icon: false
    font_face: "Microsoft YaHei"
    font_point: 12
    fullscreen: false
    horizontal: true
    inline_preedit: false
    label_format: "%s."
    layout: {border_width: 3, candidate_spacing: 5, hilite_padding: 2, hilite_spacing: 4, margin_x: 12, margin_y: 12, min_height: 0, min_width: 160, round_corner: 4, spacing: 10}
    preedit_type: composition
  "style/color_scheme": metroblue
```

1、我之前电脑的weasel 已经回退到0.14.3
2、我在另外一台 win 11 21H2 的电脑上未能复现问题。
3、win11 22h2 未做过字体相关的设置。
4、我准备在有问题的电脑上，进行一次weaseld的清洁安装。
