### ISSUE TITLE
修改简/繁体字快捷键方案

### ISSUE THREAD

**Issue by 239144498** [rime/weasel#850]
今天刚使用这款开源的输入法，之前一直用的windows系统默认的，用习惯了`ctrl+shift+f`快捷键切换简/繁体字，在看完文档后自己改回了windows切换切换简/繁体字方案，特意分享教程给大家，希望对有需要的人有所帮助。

教程地址：https://www.cnblogs.com/1314h/p/17298555.html

**Comment by pdog18** [comment]
```
    - when: always
      accept: Control+Shift+dollar
      toggle: simplification
```
toggle 的目标要看 switch 默认的好像是 `simplification` 然后按键 F 我记得是小写的 f 才有效？可能我记错了

**Comment by Latomoyocarl** [comment]
首先感谢楼主提供的方案！我一开始发现原本的代码并不管用，所以在原方案基础上，改进并提供我的解决方案。
```
patch:
  key_binder:
    bindings:
      - { when: always, accept: "Control+Shift+F", toggle: traditionalization }  
```
我是把以上方案放在 `default.custom.yaml` 文件里，别的地方没有写，经测试能用。但是写成 `zh_simp` 或 `simplification` 反而不能用，不清楚原因。
