### ISSUE TITLE
<>符号问题

### ISSUE THREAD

**Issue by queyuewutong** [rime/weasel#857]
请问新版小狼毫输入界面的<>符号可以关闭吗？在哪里关闭啊？

**Comment by fxliang** [comment]
```yaml
preset_color_schemes/xxx/prevpage_color: 0x00000000 #default transparent
preset_color_schemes/xxx/nextpage_color: 0x00000000 #default transparent
# if both prevpage_color and nextpage_color not transparent, pager mark button will be shown when no inline_preedit
```
已默认透明不绘制，如需使能需两个颜色值都设置为非透明色
