### ISSUE TITLE
最新的CI中， key_binder 绑定 switches 中的选项后表现异常

### ISSUE THREAD

**Issue by shitlime** [rime/weasel#878]
在最新的的CI <https://github.com/rime/weasel/actions/runs/5031890371> 中，有如下问题：

`schema.yaml`方案文件:

`key_binder/bindings` 配置按键绑定：
```yaml
key_binder:
  bindings:
    - { when: always, accept: Control+Shift+F, toggle: s2t } #繁简体切换
```

`switches` 中配置的候选栏选项：
```yaml
switches:  # 开关
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - options: [ noop, s2t, s2tw, s2hk, s2jp ]
```

当实际使用时，  
release版中表现为按 `Control+Shift+F` 后开/关 `s2t` 滤镜；  
而在最新的CI中，表现为 **按5次开/关 `s2t` 滤镜** .

按5次 `Control+Shift+F` 期间，**并不会** 开启 `- options: [ noop, s2t, s2tw, s2hk, s2jp ]` 中的其他滤镜，这明显是bug，希望能尽快发现原因。
