### ISSUE TITLE
辅码造词在两个词都以辅码输入时候造词失败，后面的字不以辅码输入就可以造词。但是进入词库的编码都是有辅码的

### ISSUE THREAD

**Issue by BigOldTree** [rime/weasel#902]
比如下面，“有先” 这个词
![动画](https://github.com/rime/weasel/assets/95293685/58e75cdb-5cef-45bf-ba63-0ddb1cef7a1b)

用户词库中的
![image](https://github.com/rime/weasel/assets/95293685/5a0cc20a-d575-4fd1-b142-1b6085ea33f5)

**Comment by determ1ne** [comment]
其他平台上的 rime 是否有这个问题？

**Comment by BigOldTree** [comment]
> 其他平台上的 rime 是否有这个问题？
没有平台没有测试，主要是在window 平台上使用

**Comment by BigOldTree** [comment]
> 其他平台上的 rime 是否有这个问题？

刚在deepin linux v23 上使用的fcitx5-rime ，相同的配置也有这样的问题

**Comment by BigOldTree** [comment]
下面是方案配置，码表词库使用的是小鹤音形

```
schema:
  schema_id: flypy_flypy
  name: 小鹤双拼+形辅助码
  version: "0.15"
  author:
    - aerian
  description: |
    小鹤双拼+辅助码方案
  dependencies: 
    - stroke

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]
  - name: ascii_punct
    states: [ 。，, ．， ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
  filters:
    - simplifier
    - uniquifier

speller:
  alphabet: "zyxwvutsrqponmlkjihgfedcba;"
  delimiter: " '"
  max_code_length: 5
  auto_select: true   #全码唯一自动上屏，无则后码顶上屏
  auto_select_unique_candidate: true #无重码自动上屏
  algebra:
    - derive/^(\w*);(\w)(\w)$/$1;$2$3/
    - derive/^(\w*);(\w)(\w)$/$1;$2/
    - derive/^(\w*);(\w)(\w)$/$1/
    # 以下是模糊音配置
    # eng<->en 之间映射
    - "derive/^(\\w)g;(\\w)(\\w)$/$1f;$2$3/"
    - "derive/^(\\w)g;(\\w)(\\w)$/$1f;$2/"
    - "derive/^(\\w)g;(\\w)(\\w)$/$1f/"
    - "derive/^(\\w)f;(\\w)(\\w)$/$1g;$2$3/"
    - "derive/^(\\w)f;(\\w)(\\w)$/$1g;$2/"
    - "derive/^(\\w)f;(\\w)(\\w)$/$1g/"
    # in<->ing 之间映射
    - "derive/^(\\w)b;(\\w)(\\w)$/$1k;$2$3/"
    - "derive/^(\\w)b;(\\w)(\\w)$/$1k;$2/"
    - "derive/^(\\w)b;(\\w)(\\w)$/$1k/"
    - "derive/^(\\w)k;(\\w)(\\w)$/$1b;$2$3/"
    - "derive/^(\\w)k;(\\w)(\\w)$/$1b;$2/"
    - "derive/^(\\w)k;(\\w)(\\w)$/$1b/"
    # c<->ch 之间映射
    - "derive/^z(\\w);(\\w)(\\w)$/v$1;$2$3/"
    - "derive/^z(\\w);(\\w)(\\w)$/v$1;$2/"
    - "derive/^z(\\w);(\\w)(\\w)$/v$1/"
    - "derive/^v(\\w);(\\w)(\\w)$/z$1;$2$3/"
    - "derive/^v(\\w);(\\w)(\\w)$/z$1;$2/"
    - "derive/^v(\\w);(\\w)(\\w)$/z$1/"
    # c<->ch 之间映射
    - "derive/^c(\\w);(\\w)(\\w)$/i$1;$2$3/"
    - "derive/^c(\\w);(\\w)(\\w)$/i$1;$2/"
    - "derive/^c(\\w);(\\w)(\\w)$/i$1/"
    - "derive/^i(\\w);(\\w)(\\w)$/c$1;$2$3/"
    - "derive/^i(\\w);(\\w)(\\w)$/c$1;$2/"
    - "derive/^i(\\w);(\\w)(\\w)$/c$1/"
    # s<->sh 之间映射
    - "derive/^s(\\w);(\\w)(\\w)$/u$1;$2$3/"
    - "derive/^s(\\w);(\\w)(\\w)$/u$1;$2/"
    - "derive/^s(\\w);(\\w)(\\w)$/u$1/"
    - "derive/^u(\\w);(\\w)(\\w)$/s$1;$2$3/"
    - "derive/^u(\\w);(\\w)(\\w)$/s$1;$2/"
    - "derive/^u(\\w);(\\w)(\\w)$/s$1/"

translator:
  dictionary: flypy_flypy
  prism: flypy_flypy
  contextual_suggestions: true  # 开启八股文, 上下文联想
  encode_commit_history: true   # 上屏历史记录
  initial_quality: 1.3
  spelling_hints: 1            ## `0`: 关闭单字编码提示
  comment_format:
    - xform/^\w+[;](\w+)$/~$1/                   ## 单字编码提示只显示辅助码部分
    - xform/^~\w+\s.*$//                         ## 单字编码提示只显示辅助码部分
punctuator:
  import_preset: default

key_binder:
  import_preset: default

```
