### ISSUE TITLE
部分情况下，Word中候选框会发生上下抖动

### ISSUE THREAD

**Issue by s92671** [rime/weasel#913]
系统：Win10 LTSC 21H2
word版本：Office LTSC 2021，已关闭“输入法控制处于活动状态”选项
印象很多版本的weasel都有这个问题。

如下图，第2、5、8行输入时，候选框会上下1个像素的抖动。
经多次尝试，未发现抖动的触发原因，与字体等word格式无关，但发生抖动的行固定间隔为3行或2行。

当inline_preedit设置为false，在发生抖动的行输出时，候选框显示后立即下移1个像素，但随后位置固定，不再抖动（即候选框仅在显示时抖动一下，不会持续抖动）

![11](https://github.com/rime/weasel/assets/40166/ef6ebcee-52bf-4c94-a16c-9987ab53b8b1)

**Comment by s92671** [comment]
> 暂未复现问题
> 
> 不过你可以试试我新改的一点东西（有加参数记得重新登陆一下） https://github.com/fxliang/weasel/actions/runs/5220533286

测试了一下，还是有抖动
这个问题我在另外一台电脑上同样无法复现
![23](https://github.com/rime/weasel/assets/40166/2a058faa-b150-4104-8188-928a5e620967)

**Comment by crackself** [comment]
我在Firefox浏览器中发现weasel-0.15.0.0版本输入框会跳到最左上角（开始输入时在左上角，继续输入则恢复到光标跟随位置）
测试环境：
Win11 22H2 22621.1702  64 位
Firefox 114.0.1  64 位
Microsoft Edge  113.0.1774.57  64 位
![输入法](https://github.com/rime/weasel/assets/16448332/c8e3ec61-a5d4-4fd4-995a-0a269dbe1048)

**Comment by s92671** [comment]
我在另外一台电脑上复现成功，并且发现候选框抖动的一个情况，供参考：
发生抖动的候选框均位于光标的下方，当候选框显示在光标上方时，就不再发生抖动。

![123](https://github.com/rime/weasel/assets/40166/7d549ae2-1a57-41ec-8472-202b2997b3d0)

**Comment by fxliang** [comment]
一直没有复现一样的问题...或者试下下面的这个，位置的计算稍修改了点东西
https://github.com/fxliang/weasel/actions/runs/5235685888

**Comment by s92671** [comment]
最新构建[5f07acc](https://github.com/fxliang/weasel/commit/5f07acca17bbecd80ef9cfba184265933a7f320d)测试还是有同样的问题

**Comment by fxliang** [comment]
始终没有复现出来问题，方便的话，发一下样式配置文件吧

**Comment by s92671** [comment]
`patch:
    show_notifications_when: appropriate # 状态通知，appropriate 可设为全开（always）全关（never）
    style:
        color_scheme: personal # 所用皮肤名
        display_tray_icon: true # 状态栏图标
        horizontal: false # 候选词横向
        inline_preedit: true # 拼音行是否显示在皮肤内，即单行显示true或多行显示false
        label_format: "%s." # 序号的显示格式
        font_face: "微软雅黑"
        font_point: 12
        # label_font_face: Tahoma # 序号的字体
        label_font_point: 11 # 序号字体大小
        # blur_window: true # 毛玻璃效果，设置后shadow_color失效
        mark_text: "" # 已选候选字前缀的标签
        layout:
            hilite_spacing: 6 # 序号和候选词之间的间距
            # hilite_spacing: 2 # 序号和候选词之间的间距
            hilite_padding: 3
            border_width: 1 # 皮肤边框线条宽度
            round_corner: 2 # 所选候选词高亮圆角
            corner_radius: 4 # 窗口圆角
            candidate_spacing: 6 # 候选词之间间距
            margin_x: 5 # 需考虑 border_width + hilite_padding
            margin_y: 5
            spacing: 6 # 拼音条与候选词之间间距，在inline_preedit: true时失效
            min_width: 160
            min_height: 20
            max_width: 1000 # 超过后自动换行
            max_height: 0
            shadow_offset_x: 2
            shadow_offset_y: 2
            shadow_radius: 2 # 阴影扩散效果
    preset_color_schemes:
        personal:
            name: "自用"
            color_format: rgba # 24位色值，16进制 RGBA
            # 拼音行设置在inline_preedit: true时失效
            text_color: 0xff0000 # 拼音行分隔符颜色
            hilited_text_color: 0x000000 # 拼音行颜色
            hilited_back_color: 0xe8e8e9 # 拼音行背景色
            # hilited_shadow_color: 0x000000 # 拼音行阴影
            border_color: 0x666666 # 边框颜色
            back_color: 0xe8e8e9 # 候选条背景色
            label_color: 0x666666 # 候选词序号颜色
            candidate_text_color: 0x000000 # 候选词文字颜色#000000
            comment_text_color: 0x999999 # 候选词提示文字颜色
            hilited_candidate_text_color: 0xFF0000 # 已选候选字文字颜色
            hilited_candidate_back_color: 0xd4d4d6 # 已选候选字背景色
            hilited_candidate_border_color: 0xa8aaac # 已选候选字边框颜色
            # hilited_candidate_shadow_color: 0xcccccc # 已选字阴影
            hilited_label_color: 0x666666 # 已选字序号颜色
            # hilited_mark_color: 0x0000ff # 已选候选字前缀的标签颜色，与mark_text对应
            shadow_color: 0x000000aa # 窗口阴影颜色
            prevpage_color: 0x000000 # 上翻页按键颜色
            nextpage_color: 0x000000 # 下翻页按键颜色
`

**Comment by s92671** [comment]
```
patch:
    show_notifications_when: appropriate # 状态通知，appropriate 可设为全开（always）全关（never）
    style:
        color_scheme: personal # 所用皮肤名
        display_tray_icon: true # 状态栏图标
        horizontal: false # 候选词横向
        inline_preedit: true # 拼音行是否显示在皮肤内，即单行显示true或多行显示false
        label_format: "%s." # 序号的显示格式
        font_face: "微软雅黑"
        font_point: 12
        # label_font_face: Tahoma # 序号的字体
        label_font_point: 11 # 序号字体大小
        # blur_window: true # 毛玻璃效果，设置后shadow_color失效
        mark_text: "" # 已选候选字前缀的标签
        layout:
            hilite_spacing: 6 # 序号和候选词之间的间距
            # hilite_spacing: 2 # 序号和候选词之间的间距
            hilite_padding: 3
            border_width: 1 # 皮肤边框线条宽度
            round_corner: 2 # 所选候选词高亮圆角
            corner_radius: 4 # 窗口圆角
            candidate_spacing: 6 # 候选词之间间距
            margin_x: 5 # 需考虑 border_width + hilite_padding
            margin_y: 5
            spacing: 6 # 拼音条与候选词之间间距，在inline_preedit: true时失效
            min_width: 160
            min_height: 20
            max_width: 1000 # 超过后自动换行
            max_height: 0
            shadow_offset_x: 2
            shadow_offset_y: 2
            shadow_radius: 2 # 阴影扩散效果
    preset_color_schemes:
        personal:
            name: "自用"
            color_format: rgba # 24位色值，16进制 RGBA
            # 拼音行设置在inline_preedit: true时失效
            text_color: 0xff0000 # 拼音行分隔符颜色
            hilited_text_color: 0x000000 # 拼音行颜色
            hilited_back_color: 0xe8e8e9 # 拼音行背景色
            # hilited_shadow_color: 0x000000 # 拼音行阴影
            border_color: 0x666666 # 边框颜色
            back_color: 0xe8e8e9 # 候选条背景色
            label_color: 0x666666 # 候选词序号颜色
            candidate_text_color: 0x000000 # 候选词文字颜色#000000
            comment_text_color: 0x999999 # 候选词提示文字颜色
            hilited_candidate_text_color: 0xFF0000 # 已选候选字文字颜色
            hilited_candidate_back_color: 0xd4d4d6 # 已选候选字背景色
            hilited_candidate_border_color: 0xa8aaac # 已选候选字边框颜色
            # hilited_candidate_shadow_color: 0xcccccc # 已选字阴影
            hilited_label_color: 0x666666 # 已选字序号颜色
            # hilited_mark_color: 0x0000ff # 已选候选字前缀的标签颜色，与mark_text对应
            shadow_color: 0x000000aa # 窗口阴影颜色
            prevpage_color: 0x000000 # 上翻页按键颜色
            nextpage_color: 0x000000 # 下翻页按键颜色

```

**Comment by fxliang** [comment]
基本破案，原因是word里面获取到的输入bottom座标存在波动，y轴一个像素的跳动
试试这个看看效果
https://github.com/fxliang/weasel/actions/runs/5251423753

**Comment by s92671** [comment]
@fxliang 这个用起来不会抖动了👍

**Comment by Techince** [comment]
> 我在Firefox浏览器中发现weasel-0.15.0.0版本输入框会跳到最左上角（开始输入时在左上角，继续输入则恢复到光标跟随位置） 测试环境： Win11 22H2 22621.1702 64 位 Firefox 114.0.1 64 位 Microsoft Edge 113.0.1774.57 64 位 ![输入法](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)

把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。

**Comment by crackself** [comment]
> > 我在Firefox浏览器中发现weasel-0.15.0.0版本输入框会跳到最左上角（开始输入时在左上角，继续输入则恢复到光标跟随位置） 测试环境： Win11 22H2 22621.1702 64 位 Firefox 114.0.1 64 位 Microsoft Edge 113.0.1774.57 64 位 ![输入法](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> >       
> >         [
> >           
> >         
> >             ![输入法](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> >           ](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> 
> 把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。

已测试，无改变。

**Comment by Techince** [comment]
> > > 我在Firefox浏览器中发现weasel-0.15.0.0版本输入框会跳到最左上角（开始输入时在左上角，继续输入则恢复到光标跟随位置） 测试环境： Win11 22H2 22621.1702 64 位 Firefox 114.0.1 64 位 Microsoft Edge 113.0.1774.57 64 位 ![输入法](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > >       
> > >         [
> > >           
> > >         
> > >             ![输入法](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > >           ](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         ![输入法](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > >       ](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/16448332/244908252-c8e3ec61-a5d4-4fd4-995a-0a269dbe1048.gif)
> > > ```
> > 
> > 
> > 把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。
> 
> 已测试，无改变。

内嵌样式不存在此问题，可以先临时用「"style/inline_preedit": true」来解决。梁大正在处理。

**Comment by fxliang** [comment]
@crackself 留意这个有没有修好，试一点时间，确认了我再看pr
https://github.com/fxliang/weasel/actions/runs/5290931214

**Comment by crackself** [comment]
> @crackself 留意这个有没有修好，试一点时间，确认了我再看pr https://github.com/fxliang/weasel/actions/runs/5290931214

感谢更新，此版本未复现该问题。另外`weasel.custom.yaml`设置如下：
```
patch:
  # 外觀設置
  "style/horizontal": true    # 橫排候選字
  #"menu/page_size": 5         # 候選字數量 在default.custom.yaml中设置
  "style/font_face": "微软雅黑"  # 字體名稱，從記事本等處的系統字體對話框裏能看到
  "style/font_point": 18     # 字號，只認數字的，不認「五號」、「小五」這樣的
  "style/inline_preedit": false  # 候选窗 不显示内选区(即拼音区)  
  "style/layout/border": 2    # 候选框边框粗细
  "style/layout/candidate_spacing": 10   # 候选字间隔
  "style/layout/hilite_padding": 9    # 候选字背景色色块高度
  "style/layout/hilite_spacing": 2    # 序号和候选字之间的间隔
  "style/layout/margin_x": 9    # 候选框左右边距
  "style/layout/margin_y": 9    # 候选框上下边距
  "style/layout/round_corner": 13    # 候选字背景色块圆角半径
  "style/display_tray_icon" : true    # 显示托盘图标
  #
  # 額外主題
  "style/color_scheme": WeChat-keyboard   # 設置主題
  "preset_color_schemes/WeChat-keyboard":
    name: WeChat-keyboard # 配色取自微信键盘
    author: crackself@gmail.com
    back_color: 0x4D4D4D # 背景
    border_color: 0x4D4D4D # 边框 0为白色，F为黑色
    text_color: 0x00FF11 #输入区文字颜色
    hilited_text_color: 0xC300FF # 输入区高亮文字颜色
    hilited_back_color: 0x4D4D4D # 输入区高亮背景
    hilited_candidate_text_color: 0x0000FF # 第一候选项文字颜色
    hilited_candidate_back_color: 0xDBDBDB # 第一候选项背景颜色
    hilited_comment_text_color: 0x999999 # 注解文字高亮
    candidate_text_color: 0x00FFFF # 其他候选项文字颜色
    comment_text_color: 0x0000FF # 其他候选项注解文字
    label_color: 0xcac9c8 # 预选栏编号颜色
  #
```
