### ISSUE TITLE
0.15.0 新增加的 composition 模式下的下划线提示是否有选项关闭？

### ISSUE THREAD

**Issue by Eason0210** [rime/weasel#915]
在最新发布的 0.15.0 中，新增了 composition 模式下的下划线提示，这个功能在候选窗口跟随输入移动时是有用的。
但的如果候选窗口不移动（ #912 ）的情况下，下划线提示反而会影响美观。
如下图中，同时设置了圆角时就会看到一点下划线。希望有个选项可以关闭下划线提示。

![image](https://github.com/rime/weasel/assets/47546452/2b32d30f-efa8-4036-921c-5536d6748ea5)

**Comment by determ1ne** [comment]
这个功能并不算新增的，而是取代原先用选中表示 composition 的行为，下划线的意义是区分已经写好的文字与输入法正在编辑的文字

**Comment by Eason0210** [comment]
> 下划线的意义是区分已经写好的文字与输入法正在编辑的文字
你这么说是有用的，特别是在 Word 中，没有高亮当前行时，下划线提示作用就很大，也没必要关闭它。

![image](https://github.com/rime/weasel/assets/47546452/3c673bb7-e251-4a0e-aa3c-eff9d66c6c6f)

而且在 Word 中，是全部看的见下划线的，在 notepad3 中是被候选框挡了，只在圆角部分看得见。
看来这只是 weasel 在不同的应用程序中渲染的差异。

**Comment by Mr54233** [comment]
大佬，能否给一份你这个皮肤的配置。谢谢

**Comment by Eason0210** [comment]
> 大佬，能否给一份你这个皮肤的配置。谢谢
可以参考我的 `weasel.custom.yaml` 设置：
```
patch:
  # 以下软件默认英文模式
  app_options/windowsterminal.exe:
    ascii_mode: true

# 以下为候选框界面的样式设置
  __include: macos

macos:
  style/color_scheme: so_young
  style/color_scheme_dark: so_young
  style/color_font: true
  style/horizontal: true                         # 横排显示
  style/inline_preedit: true                     # 嵌入式候选窗单行显示
  style/layout/enhanced_position: true
  style/font_face: "LXGW Wenkai, Microsoft YaHei"             # 候选字字体
  style/font_point: 16                           # 候选字字体大小
  style/comment_font_face: "LXGW Wenkai, Microsoft YaHei"     # 注解字体
  style/comment_font_point: 16                   # 注解字体大小
  style/label_font_point: 13                     # 序号字体大小
  style/label_format: "%s"                       # 取消序号和候选字之间的点号
  style/layout/border_width: 1                   # 条边框宽度
  style/layout/border_hight: 1                   # 条边框高度
  style/layout/border_color_width: 0             # 候选窗边框宽度
  style/layout/candidate_spacing: 20             # 候选字间隔
  style/layout/corner_radius: 5                 # 边框的圆角幅度
  style/layout/round_corner: 5                   # 第一候选字高亮颜色的圆角,别名 hilited_corner_radius
  style/layout/margin_x: 8                       # 起始候选字的左边距
  style/layout/margin_y: 8                       # 候选字的上下边距
  style/layout/min_width: 50                     # 候选窗最小宽度
  style/layout/max_width: 1250                   # 候选窗最大宽度
  style/layout/hilite_padding: 4                 # 候选字背景色色块高度
  style/layout/hilite_spacing: 4                 # 序号和候选字之间的间隔
  style/layout/shadow_radius: 5                  # 全局阴影模糊半径，如果为0则全局禁用阴影
  style/layout/shadow_offset_x: 0                # 阴影x偏置
  style/layout/shadow_offset_y: 2                # 阴影x偏置
  style/layout/align_type: bottom                # 字体对齐,可选值：center,bottom
  preset_color_schemes/so_young:
    name: "致青春／So Young"
    author: "五磅兔 <zcunlin@foxmail.com>"
    text_color: 0x8236d3                         # 默认文字颜色
    back_color: 0xe3f6fd                         # 候选窗背景色，24位色值，16进制，BGR顺序
    border_color: 0xdcdcdc                       # 候选窗边框颜色
    label_color: 0xa1a193                        # 预选栏编号颜色
    candidate_text_color: 0x837b65               # 非高亮候选文字颜色
    comment_text_color: 0xd28b26                 # 拼音等提示文字颜色
    hilited_text_color: 0x969483                 # 编码文字颜色
    hilited_back_color: 0xd5e8ee                 # 编码背景颜色
    hilited_candidate_text_color: 0xd5e8ee       # 高亮候选文字颜色
    hilited_comment_text_color: 0xd5e8ee         # 高亮的注解文字颜色
    hilited_candidate_back_color: 0x98a12a       # 高亮的注解文字颜色
```
