### ISSUE TITLE
皮肤显示异常，没有边框

### ISSUE THREAD

**Issue by k9li** [rime/weasel#933]
**操作系统信息**
 - OS 详细版本: 22621.1702
 - 小狼豪版本: 0.15.0.0 

**描述遇到的问题**
皮肤显示异常，没有边框

**截图**
![image](https://github.com/rime/weasel/assets/3532135/23e0a329-a216-4951-b847-300cd324605e)

**Comment by k9li** [comment]
沙盒重启后也出现相同现象
![image](https://github.com/rime/weasel/assets/3532135/3091be78-b018-4d0a-afff-b83b54a15503)

**Comment by fxliang** [comment]
关键词：沙盒，影响未知

贴配置吧

**Comment by k9li** [comment]
```
patch:
  style:
    font_point: 11
    label_font_point: 11
    comment_font_point: 9
    preedit_type: "composition"
    "layout/min_width": 190
  "preset_color_schemes/X":
    name: X
    color_format: "argb"
    back_color: 0xDD222222                 # 背景
    border_color: 0x00222222               # 边框
    text_color: 0xE7FDFF                   # 头部预览文字
    hilited_text_color: 0x777E7F           # 头部编码文字
    hilited_back_color: 0x222222           # 头部编码背景
    hilited_candidate_text_color: 0xDFF8FF # 选中文字
    hilited_candidate_back_color: 0x333333 # 选中背景
    candidate_text_color: 0xDFF8FF         # 候选文字
    comment_text_color: 0x777E7F           # 候选提示文字
  "style/color_scheme": X
```

**Comment by mirtlecn** [comment]
> weasel.custom.yaml
> 
> ```
> patch:
>   style:
>     font_point: 11
>     label_font_point: 11
>     comment_font_point: 9
>     preedit_type: "composition"
>     "layout/min_width": 190
>   "preset_color_schemes/X":
>     name: X
>     color_format: "argb"
>     back_color: 0xDD222222                 # 背景
>     border_color: 0x00222222               # 边框
>     text_color: 0xE7FDFF                   # 头部预览文字
>     hilited_text_color: 0x777E7F           # 头部编码文字
>     hilited_back_color: 0x222222           # 头部编码背景
>     hilited_candidate_text_color: 0xDFF8FF # 选中文字
>     hilited_candidate_back_color: 0x333333 # 选中背景
>     candidate_text_color: 0xDFF8FF         # 候选文字
>     comment_text_color: 0x777E7F           # 候选提示文字
>   "style/color_scheme": X
> ```
> 
> 使用该配置重新部署后重启设置可重现

配置写错了，这样写 style 节点下只有你指定的这些属性, 全部改成：

```yaml
"style/font_point":
```
阅读：

https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97

**Comment by k9li** [comment]
感谢！
那确认一下，custom的配置都是覆盖patch下一级的属性？没注意到有这样的规则，抱歉

**Comment by fxliang** [comment]
看上去配置砍了很多东西的样子，看看部署生成的数据吧

**Comment by k9li** [comment]
> 看上去配置砍了很多东西的样子，看看部署生成的数据吧

```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.0.0
  generator: "Weasel::UIStyleSettings"
  modified_time: "Wed Jun 14 12:37:21 2023"
  rime_version: 1.8.5
patch:
  app_options:
    explorer.exe: {ascii_mode: true}
    searchapp.exe: {ascii_mode: true}
    startmenuexperiencehost.exe: {ascii_mode: true}
    sublime_text.exe: {ascii_mode: true}
    windowsterminal.exe: {ascii_mode: true}
    xshell.exe: {ascii_mode: true}
    xshellcore.exe: {ascii_mode: true}
  "preset_color_schemes/X":
    back_color: 0xDD222222
    border_color: 0x00222222
    candidate_text_color: 0xDFF8FF
    color_format: argb
    comment_text_color: 0x777E7F
    hilited_back_color: 0x222222
    hilited_candidate_back_color: 0x333333
    hilited_candidate_text_color: 0xDFF8FF
    hilited_text_color: 0x777E7F
    name: X
    text_color: 0xE7FDFF
  style:
    comment_font_point: 9
    font_point: 11
    label_font_point: 11
    "layout/min_width": 190
    preedit_type: composition
  "style/color_scheme": X
```
