### ISSUE TITLE
一些罕见字在字库里却打不出来

### ISSUE THREAD

**Issue by Adrakaris** [rime/weasel#955]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.3086
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
一些罕见字在字库内却打不出来。

我的字库是修改的五笔86版：https://github.com/Adrakaris/rime-setup/blob/master/wubi86.dict.yaml  与 https://github.com/Adrakaris/rime-setup/blob/master/wubi86.schema.yaml

这些罕见字包括：㕧 (KNT)、𪚥 (UEGD) 以及任何weight很小的或者0的字。

**复现步骤**
重现问题的步骤，如：
1. 选择「中州五笔86修改」输入法
2. 在任何地方试图输入以上所提之字

**预期行为**
我猜是某一个设定我没找到，而这不是Bug。

**用户文件**
[用户.zip](https://github.com/rime/weasel/files/11910847/default.zip)

**Comment by Adrakaris** [comment]
我找到了，是个我错过的设定

`translator`下`enable_charset_filter` 要设成 `false`

既然如此，请问该`enable_charset_filter`是具体是在做什么，是哪些Character sets，有没有更细的控制方法？在哪里可以找到schema设定相应的文档？

**Comment by zhifuchen** [comment]
按ctrl+`,切换常用字库为扩展字库

**Comment by zhifuchen** [comment]
我想知道输入法是怎么判断哪些是常用字哪些是扩展字的

**Comment by zhifuchen** [comment]
我想知道输入法是怎么判断哪些是常用字哪些是扩展字的@Techince

**Comment by Techince** [comment]
有规范的，字符集有GB2312、GBK和GB18030。早期用五笔时，一般的常用字都是在GB2312范围内的，后来需要用到GBK字符集里的字，然后五笔的重码码会上升。转到郑码后，郑码默认GB18030字符集，大多生僻字都能显示，郑码群也有人不断在更新新增的字符。

**Comment by Adrakaris** [comment]
> 按ctrl+`,切换常用字库为扩展字库

@zhifuchen 我用ctrl+`时只有切换输入方法，似乎没有切换字库的设定。我需要自己去schema里将true改成false才能的。有哪里可以让这个功能出现吗？

**Comment by Adrakaris** [comment]
好了我琢磨出来了，在该schema里`switches`下加一个：

```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: extended_charset
    states: [ 常, 扩 ]
```
