### ISSUE TITLE
全拼方案中的简拼规则会引入模糊音问题

### ISSUE THREAD

**Issue by Lantaio** [rime/weasel#973]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 10 简体中文企业版 LTSC，版本 1809，内部版本 17763.1879 ]
 - 小狼毫版本: [ 0.15.0.0，Commit CI #122 ]

**描述遇到的问题**
由于全拼重码很多，所以我一般不开启z、c、s、zh、ch、sh模糊音。但发现即使不开启相关的模糊音规则，软件默认的简拼规则也会导致开启zh、ch、sh模糊音，导致输入z、c、s时出现大量不希望出现的重码。软件默认的简拼规则如下：
``` yaml
speller:
  algebra: # 模糊音
    - abbrev/^([a-z]).+$/$1/ # 簡拼（首字母）
    - abbrev/^([zcs]h).+$/$1/ # 簡拼（zh, ch, sh）
```
简拼（首字母）规则导致在输入z、c、s时，连zh、ch、sh都满足条件。例如：输入`cs`，则“测试”（ce shi）、“城市”（cheng shi）都在候选项列表中。

**复现步骤**
小狼毫0.14.3版和0.15.0版都存在这个问题。

**预期行为**
由于全拼本身重码就多，所以不希望在输入z、c、s时在候选中出现zh、ch、sh候选字词。

**其他补充说明**
我瞎折腾了一下，改成下面的样子，好像可以实现我的预期目的。不过因为正则表达式对我来说是天书，因此我也不确定对不对，或者会不会引入别的问题或bug，所以请开发团队看看下面的修改有没有问题？
``` yaml
speller:
  algebra: # 模糊音
    - abbrev/^([a-z])[^h]+$/$1/ # 簡拼（首字母，后续字母不是h）
    - abbrev/^([zcs]h).+$/$1/ # 簡拼（zh, ch, sh）
```
当然，可能写成下面这样更严谨一点
``` yaml
speller:
  algebra: # 模糊音
    - abbrev/^([abd-rt-y]).+$/$1/ # 簡拼（除z、c、s之外的首字母）
    - abbrev/^([zcs])[^h]+$/$1/ # 简拼（z，c，s）
    - abbrev/^([zcs]h).+$/$1/ # 簡拼（zh, ch, sh）
```
不过如果第1种写法没有问题的话，那么是不是第1种写法少了一条规则速度会更快？
初步测试了一下，这样修改之后好像不会出现模糊音候选项，然后如果想开启zh、ch、sh模糊音规则好像也是可以的。
