### ISSUE TITLE
CI 125 版本 style 中的 preedit_type: preview 属性失效，显示编码而非高亮候选

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#976]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用最新发布版本后的 CI 构建

**操作系统信息**
 - Windows 10 21H2 19044.3086
 - [CI 125](https://github.com/rime/weasel/actions/runs/5612463045)

**描述遇到的问题**
新 CI 版本 style 中的 preedit_type: preview 属性失效。表现为仍然显示编码而非高亮候选。

[CI 109](https://github.com/rime/weasel/actions/runs/5340462463) 无此问题

**build 下的 weasel.yaml**

```yaml
  mark_text: "|"
  preedit_type: preview
  vertical_auto_reverse: false
  vertical_text: false
  vertical_text_left_to_right: false
  vertical_text_with_wrap: false
```
