### ISSUE TITLE
中英文切换 switch_key 可否定义为组合键？

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [rime/weasel#98]
<s>我看到文档和其他issue，没有提到`default.yaml`的自定义里面，`ascii_composer/switch_key`部分中英文切换可否修改为组合键，是否已有此功能？`shift`被我频繁用于打大写字母，很可能无意换成中文。感谢。如不行也不要紧，我就问问。</s>此条我已找到其他贴解决，看回复。

另外我看到CustomizationGuide部分，有个链接失效了：
> 按鍵的名稱，大小寫字母和數字都用他們自己表示，其他的按鍵名稱 參考這裏 这个更直观的文档 的定義，去除代碼前綴 XK_ 即是。

`参考这里`页面似乎飞走了。

**Comment by WesleyBlancoYuan** [comment]
找到了，可在`default.custom.yaml`里面加入热键定义：

```
  ascii_composer/switch_key:
     Shift_L: noop    #禁用
     Shift_R: noop    #禁用
  key_binder:
    bindings:
      - {accept: "Control+F1", toggle: ascii_mode, when: always}    #不要使用Alt，解释为控制键，无法读取快捷键。https://github.com/rime/home/issues/152

```
