### ISSUE TITLE
0.14.3.0怎样关闭自动造词？手动造词编辑哪个文件？

### ISSUE THREAD

**Issue by jzmswe** [rime/weasel#984]
如果只解决前一个问题也行，后一个问题，我可以建个TXT文件导入，就是麻烦了一点。

**Comment by wzxmer** [comment]
这个跟rime无关，跟你使用的方案有关系，需要你更改自己的方案。

**Comment by fxliang** [comment]
方案名.custom.yaml例子
```yaml
patch:
  translator/enable_user_dict: false  # 禁用用户词典

  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase  # custom_phrase.txt
    db_class: stabledb
    enable_completion: false
    enable_sentence: false
    initial_quality: 1

  engine/translators/@after last: table_translator@custom_phrase  # 增加custom_phrase翻译器

```

custom_phrase.txt例子
```yaml
# Rime table
# coding: utf-8
#@/db_name custom_phrase.txt
#@/db_type tabledb
#
# 用於【五笔】系列輸入方案
# 【小狼毫】0.9.21 以上
#
# 請將該文件以UTF-8編碼保存爲
# Rime用戶文件夾/custom_phrase.txt
#
# 碼表各字段以製表符（Tab）分隔
# 順序爲：文字、編碼、權重（決定重碼的次序、可選）
#
# 雖然文本碼表編輯較爲方便，但不適合導入大量條目
#

# 有效的词条组成方式   词条\TAB编码\TAB1
# \TAB表示一个Tab键，不能用空格，要用Tab
# 只要不是以这种结构的以#开始的词条就是可以认为是备注句子
# 以下no comment之后不能加注释
# no comment

一个例子	gwwb	1
```
