### ISSUE TITLE
如何设置为默认中文

### ISSUE THREAD

**Issue by j4keq** [rime/weasel#987]
如何设置为默认中文。
不是默认输入法，默认已经是小狼毫了。

我想要的是中文，在任何软件、在任何时候，一开机就是中文了马上使用。不用再Shift切换了。

有没有办法设置为中文，强制性的。中文在先英文后，和现在反过来，只有我每次Shift切换才能换回英文，不然英文不会显示。就算是在系统文件夹管理器还是任何输入下，必先中文。

这个如何实现，有没有办法，就算删掉小狼毫的英文输入也在所不惜。

**Comment by MOldtime** [comment]
首先说一下 目前的输入法是不同的窗口有不同的模式
想要更改这个问题 可以看下这个提交
https://github.com/rime/weasel/pull/856
我认为这个最优解

**Comment by yanhuacuo** [comment]
如果你没有在其他地方引入「中英文状态」（估计也没有）的话，仅需在 schema 文件中，修改一下参数：

````
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中,英 ]    
````
