### ISSUE TITLE
候选窗口不在光标下几率暴增

### ISSUE THREAD

**Issue by Huandeep** [rime/weasel#989]
通过切换回这个版本[ [13c3081](https://github.com/fxliang/weasel/commit/13c3081def28af70aaf7f71bb6f2ddd1fb07303a) ]暂时解决了。

**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 [fxliang](https://github.com/fxliang)/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 Insider Preview 23526.1000 ]
 - 小狼毫版本: [ [8309375](https://github.com/fxliang/weasel/commit/8309375e5c5d6df4406167ad761f3d3638c7fd1f)]

**描述遇到的问题**
候选窗口飘忽不定

**复现步骤**
重现问题的步骤，如：
1. 随机打开软件输入，在第一次输入或者输入后等几秒后再输入，很大几率出现

**用户文件**

```yaml
# rao 自定义皮肤
#
rao_styles:
  __include: rao_color_schemes
  # __include: rao_style_demo   # 非嵌入编码 直角 有边距
  # __include: rao_common_01    # 非嵌入编码 直角 有边距
  __include: rao_common_02    # 非嵌入编码 圆角 无边距
  # __include: rao_inline_01    # 嵌入编码 直角 有边距
  # __include: rao_inline_02    # 嵌入编码 圆角 有边距 
  # __include: rao_inline_03    # 嵌入编码 直角 无边距
  # __include: rao_inline_04    # 嵌入编码 圆角 无边距

#[程序]
  app_options:
    OpenConsole.exe:
      ascii_mode: true
    wt.exe:
      ascii_mode: true
    WindowsTerminal.exe:
      ascii_mode: true
    cmd.exe:
      ascii_mode: true
    conhost.exe:
      ascii_mode: true
    firefox.exe:
      inline_preedit: true

#[主配置]
# 非嵌入编码

rao_common_01:
  __include: rao_style_demo
  style/inline_preedit:               false
  style/layout/min_height:            208
  style/layout/min_width:             180

rao_common_02:
  __include: rao_style_demo
  style/inline_preedit:               false
  style/layout/min_height:            166
  style/layout/min_width:             180
  style/layout/margin_x:              10
  style/layout/margin_y:              5
  style/layout/corner_radius:         8
  style/layout/round_corner:          5

# 嵌入编码
rao_inline_01:
  __include: rao_style_demo
  style/inline_preedit:               true
  style/layout/min_height:            176
  style/layout/min_width:             180

rao_inline_02:
  __include: rao_style_demo
  style/inline_preedit:               true
  style/layout/min_height:            166
  style/layout/min_width:             180
  style/layout/margin_x:              10
  style/layout/margin_y:              5
  style/layout/corner_radius:         8
  style/layout/round_corner:          5

# margin_x&margin_y为0的情况下适合有"mark"颜色(非透明)及符号的主题
# 当前仅为"SGIM_doctor"主题设置
rao_inline_03:
  __include: rao_style_demo
  style/inline_preedit:               true
  style/mark_text:                    "·"
  style/layout/min_height:            160
  style/layout/min_width:             180
  style/layout/margin_x:              0
  style/layout/margin_y:              0
  style/layout/corner_radius:         0
  style/layout/round_corner:          0

rao_inline_04:
  __include: rao_style_demo
  style/inline_preedit:               true
  style/mark_text:                    "·"
  style/layout/min_height:            160
  style/layout/min_width:             180
  style/layout/margin_x:              0
  style/layout/margin_y:              0
  style/layout/corner_radius:         8
  style/layout/round_corner:          5

# 主要配置
rao_style_demo:
  style:
    # 主题
    color_scheme:                     SGIM_doctor   # (SGIM_doctor/SGIM_plain/SGIM_original/QQIM)
    # 字体
    color_font:                       false
    font_face:                        "PingFang SC:Light, LXGW WenKai, Sarasa Gothic SC, Microsoft Yahei"
    comment_font_face:                "PingFang SC:Light, LXGW WenKai, Sarasa Gothic SC, Microsoft Yahei"
    label_font_face:                  "Consolas"
    # 字号
    font_point:                       15            # 候选字号
    comment_font_point:               15            # *注释字号,小于等于候选字号
    label_font_point:                 12            # *序号字号,小于等于候选字号
    # 候选显示
    antialias_mode:                   grayscale     # 抗锯齿 (default/cleartype/grayscale/aliased/force_dword)
    fullscreen:                       false         # 全屏
    horizontal:                       false         # 横排/竖排
    inline_preedit:                   false         # 嵌入编码
    preedit_type:                     composition   # 提示类型 (composition/preview/preview_all)
    enhanced_position:                false          # 允许在光标位置获取失败时于窗口左上角绘制候选框(而不是桌面左上角)
    # 序号符号
    label_format:                     "%s"          # 编号规则
    mark_text:                        ""            # 高亮标记符号
    # 竖直布局
    vertical_auto_reverse:            false         # 在位置不够时,候选倒序
    vertical_text:                    false
    vertical_text_left_to_right:      false
    vertical_text_with_wrap:          false
    # 其他
    mouse_hover_ms:                   0             # 控制鼠标悬停响应间隔,设置为0 时禁用该功能(默认)
    paging_on_scroll:                 true          # 滚轮上下方向选字或滚轮翻页.默认为false,进行上下方向选字;true,进行翻页操作
    ascii_tip_follow_cursor:          false         # 随鼠标光标位置
    display_tray_icon:                false         # 显示托盘图标
    layout: 
      align_type:                     center        # *label和comment的位置 (bottom/center/top)
      border:                         1             # 边框宽度
      spacing:                        0             # 输入码与候选之间的间距
      candidate_spacing:              0             # 相邻候选间距
      # hilite_padding:                 2           # (旧参数)背景与文字偏离值,当设置为0时背景矩形和文字同大小
      hilite_padding_x:               5             # 背景与文字偏离值
      hilite_padding_y:               2             # 背景与文字偏离值
      hilite_spacing:                 3             # 候选内(label、text、comment)之间的相互间距
      # 候选窗
      max_height:                     600           # 最大候选窗口高度
      max_width:                      800           # 最大候选窗口宽度
      min_height:                     190           # 最小候选窗口高度
      min_width:                      170           # 最小候选窗口宽度
      margin_x:                       10            # 其绝对值为候选窗口border离候选文字边沿x距离
      margin_y:                       10            # 其绝对值为候选窗口border离候选文字边沿y距离,# 如margin_x或margin_y任一为负数,则隐藏候选窗口,不隐藏方案选单、中英切换、半角全角切换、简繁切换、错误提示
      # 圆角
      corner_radius:                  0             # 候选框窗口圆角
      round_corner:                   0             # 候选、编码背景色块圆角
      # 阴影
      shadow_radius:                  0             # *阴影模糊半径,如为0则全局关闭阴影, 当shadow_offset_x 和shadow_offset_y 都为0时圆周阴影,影响阴影大小
      shadow_offset_x:                0             # *阴影x偏置,正向右负向左
      shadow_offset_y:                0             # *阴影y偏置,正向下负向上;如果shadow_offset_x或shadow_offset_y任意一个不为零,投影阴影,否则圆周阴影

# 配色默认ABGR
rao_color_schemes:
  preset_color_schemes/SGIM_doctor:
    author: "Rao"
    name: SGIM_Doctor

    back_color: 0xFFFFFFFF                          # (候选窗)外边框
    border_color: 0xFFE3C7AB                        # (候选窗)边框颜色
    shadow_color: 0x00000000                        # (候选窗)阴影色,需开启"shadow_radius"
    prevpage_color: 0x7FB4B4B4                      # (上一页)符号颜色
    nextpage_color: 0xFF000000                      # (下一页)符号颜色

    candidate_border_color: 0x00000000              # (候选)内边框
    candidate_back_color: 0x00000000                # (候选)背景色,默认透明
    candidate_shadow_color: 0x00000000              # (候选)阴影色,默认透明
    candidate_text_color: 0xFFE58200                # (候选)文字颜色
    label_color: 0xFFE58200                         # (候选)序号颜色
    comment_text_color: 0xFF717171                  # (候选)注释颜色

    text_color: 0xFF0000FF                          # (选中)文字颜色/编码背景外的编码颜色
    hilited_back_color: 0x00000000                  # (选中)编码背景颜色
    hilited_shadow_color: 0x00000000                # (选中)编码阴影颜色,默认透明
    hilited_text_color: 0xFFC86400                  # (选中)编码文字颜色,编码背景内的编码颜色
    hilited_candidate_border_color: 0xFFC6D5FD      # (选中)候选字边框颜色,如果在alpha非0的情况下,会遮挡当"style/mark_text"为空则显示仿 Windows11 高亮选中效果
    hilited_candidate_back_color: 0xFFECF1FC        # (选中)候选字背景颜色
    hilited_candidate_shadow_color: 0x00000000      # (选中)候选阴影颜色,默认透明
    hilited_candidate_text_color: 0xFF0000FF        # (选中)候选字颜色
    hilited_comment_text_color: 0xFF000000          # (选中)候选注释文字颜色
    hilited_label_color: 0xFF0000FF                 # (选中)候选序号文字颜色
    hilited_mark_color: 0xFFC06700                  # (选中)标记符号颜色.在alpha 非0的情况下:当"style/mark_text"为空则显示仿 Windows11 高亮选中效果,如果"style/mark_text"为非空字符则为字符颜色

  # 禁用(选中)背景和标记符号颜色
  preset_color_schemes/SGIM_plain:
    author: "Rao"
    name: SGIM_plain

    back_color: 0xFFFFFFFF
    border_color: 0xFFE3C7AB
    shadow_color: 0x00000000
    prevpage_color: 0x7FB4B4B4
    nextpage_color: 0xFF000000

    text_color: 0xFF0000FF
    candidate_border_color: 0x00000000
    candidate_back_color: 0x00000000
    candidate_shadow_color: 0x00000000
    candidate_text_color: 0xFFE58200
    label_color: 0xFFE58200
    comment_text_color: 0xFF717171

    hilited_back_color: 0x00000000
    hilited_shadow_color: 0x00000000
    hilited_text_color: 0xFFC86400
    hilited_candidate_border_color: 0x00000000  # 禁用
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_shadow_color: 0x00000000
    hilited_candidate_text_color: 0xFF0000FF
    hilited_comment_text_color: 0xFF000000
    hilited_label_color: 0xFF0000FF
    hilited_mark_color: 0x00000000  # 禁用

  preset_color_schemes/SGIM_original:
    author: "Rao"
    name: SGIM_original

    back_color: 0xFFFFFFFF
    border_color: 0xFFE3C7AB
    shadow_color: 0x00000000
    prevpage_color: 0x7FB4B4B4
    nextpage_color: 0xFFDA760C

    text_color: 0xFF0000FF
    candidate_border_color: 0x00000000
    candidate_back_color: 0x00000000
    candidate_shadow_color: 0x00000000
    candidate_text_color: 0xFFE58200
    label_color: 0xFFE58200
    comment_text_color: 0xCC597AFF

    hilited_back_color: 0x00000000
    hilited_shadow_color: 0x00000000
    hilited_text_color: 0xFFB96205
    hilited_candidate_border_color: 0x00000000  # 禁用
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_shadow_color: 0x00000000
    hilited_candidate_text_color: 0xFF0000FF
    hilited_comment_text_color: 0xFF597AFF
    hilited_label_color: 0xFF0000FF
    hilited_mark_color: 0x00000000  # 禁用

  preset_color_schemes/QQIM:
    author: "Rao"
    name: QQIM

    back_color: 0xFFF9F9F9
    border_color: 0xFFE3C7AB
    shadow_color: 0x00000000
    prevpage_color: 0xFFB4B4B4
    nextpage_color: 0xFFDA760C

    text_color: 0xFF000000
    candidate_border_color: 0x00000000
    candidate_back_color: 0xFFF9F9F9
    candidate_shadow_color: 0x00000000
    candidate_text_color: 0xFFE58200
    label_color: 0xFFE58200
    comment_text_color: 0xFF52423B

    hilited_back_color: 0x00000000
    hilited_shadow_color: 0x00000000
    hilited_text_color: 0xFFB96205
    hilited_candidate_border_color: 0x00000000  # 禁用
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_shadow_color: 0x00000000
    hilited_candidate_text_color: 0xFF0000FF
    hilited_comment_text_color: 0xFF0000FF
    hilited_label_color: 0xFF0000FF
    hilited_mark_color: 0x00000000  # 禁用

#
```

**截图**
![动画](https://github.com/rime/weasel/assets/30691481/8fb5234d-fb61-4376-89e1-fc7876cf47a4)

**其他补充说明**
`app_options` 设置 `inline_preedit` 前后关于皮肤的变化有时候有点大，可不可以增加一个像是搜狗一样的皮肤设置 

![image](https://github.com/rime/weasel/assets/30691481/159cbb55-3f3b-436e-82fd-f28ca7db1066)

@fxliang
