### ISSUE TITLE
0.15版本，忽然无候选编号

### ISSUE THREAD

**Issue by wong077** [rime/weasel#992]
**操作系统信息**
 - OS 详细版本:  Windows 11 22H2 22621.2215
 - 小狼毫版本:如 0.15.0.0 

**描述遇到的问题**
横排选字，使用中忽然无候选编号，重新部署无效
<img width="260" alt="Snipaste_2023-08-30_10-02-26" src="https://github.com/rime/weasel/assets/42863677/c091041e-0311-4938-974c-ab181a367249">

[weasel.custom.zip](https://github.com/rime/weasel/files/12470990/weasel.custom.zip)

**Comment by fxliang** [comment]
配置写的不对，前面的改成这样
```yaml
patch:
  style/display_tray_icon: false
  style/inline_preedit: true
  style/horizontal: true
  style/layout/border: 0
  style/layout/margin_x: 12
  style/layout/margin_y: 12
  style/layout/hilite_padding: 12
  style/layout/hilite_spacing: 3
  style/layout/spacing: 10
  style/layout/candidate_spacing: 24
  style/layout/round_corner: 0
  style/color_scheme: ayaya

  preset_color_schemes/+:


```
